#!/bin/sh

# profile --- system-wide configuration file for shell login

# Commentary:

# This file runs on shell login; environment variables should be set here.

# Code:

# shellcheck disable=1090
# follow non-constant sources

# -----------------------------------------------------------------------------
# preamble
# -----------------------------------------------------------------------------

# == $PATH
append_path() {
    # Append "$1" to $PATH when not already in.
    # taken from '/etc/profile'
    case ":${PATH}:" in
    *:"${1}":*) ;;
    *) PATH="${PATH:+${PATH}:}${1}"
    esac
}

# load profiles from /etc/profile.d/ (os-dependant)
if test -d '/etc/profile.d/'; then
    for p in /etc/profile.d/*.sh; do
        test -r "${p}" && . "${p}"
    done
fi

# extras
append_path '/sbin/'
append_path '/usr/local/bin/'
append_path '/usr/local/sbin/'
append_path '/usr/sbin/'

# ~/.local/bin
append_path "${HOME}/.local/bin/"

# ... finally export
export PATH

# -----------------------------------------------------------------------------
# sourcing
# -----------------------------------------------------------------------------
# NOTE: ORDER MATTERS!

# this is the only envvar that should be declared here
export SH_DIR="${XDG_CONFIG_HOME:-${HOME}/.config}/sh"

. "${SH_DIR}/lib/defaults"
. "${SH_DIR}/lib/ssh"
. "${SH_DIR}/lib/xorg"
. "${SH_DIR}/lib/nix"
. "${SH_DIR}/lib/fzf"
. "${SH_DIR}/lib/langs"
