#!/bin/sh

# void
if [ -x "$(command -v "xbps-install")" ]; then
    # pkgs
    sudo xbps-install -Sy cups

    # symlink services; enable & start
    sudo ln -fs /etc/sv/cupsd /var/service
    sudo sv start cupsd
fi
