#!/bin/sh

# profile --- system-wide configuration file for shell login

# Commentary:

# This file runs on shell login; environment variables should be set here.

# Code:

# shellcheck disable=1090
# follow non-constant sources

# -----------------------------------------------------------------------------
# preamble
# -----------------------------------------------------------------------------

# == $PATH
append_path() {
    # Append "$1" to $PATH when not already in.
    # taken from '/etc/profile'
    case ":${PATH}:" in
    *:"$1":*) ;;
    *) PATH="${PATH:+${PATH}:}$1"
    esac
}

# load profiles from /etc/profile.d/
if test -d '/etc/profile.d/'; then
    for prof in /etc/profile.d/*.sh; do
        test -r "${prof}" && . "${prof}"
        unset prof
    done
fi

# extras
append_path '/sbin/'
append_path '/usr/sbin/'
append_path '/usr/local/sbin/'

# '~/.local/bin'
append_path "${HOME}/.local/bin/"

# utilities
append_path "${HOME}/.local/bin/utils"

# ... finally export
export PATH

# -----------------------------------------------------------------------------
# defaults
# -----------------------------------------------------------------------------

export EDITOR="editor"
export TERMINAL='alacritty'
export BROWSER='chromium'
export FILE='pcmanfm'
export READER='zathura'

export SHDIR="${XDG_CONFIG_HOME:-$HOME/.config}/shell"
export ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"

# -----------------------------------------------------------------------------
# extra settings
# -----------------------------------------------------------------------------
# settings are modularized in separe files for sourcing

for f in ${SHDIR}/settings/*; do
    test -x "${f}" && . "${f}"
done

# start graphical automatically
#test "$(tty)" = '/dev/tty1' && ! pgrep -x 'Xorg' >/dev/null 2>&1 && exec startx "${XORGDIR}/xinitrc"
