#!/bin/sh

# emacs-setup --- Emacs from source setup

# Commentary:

# Installs GNU Emacs from source.
# Optionally build with native compilation if `libgccjit` is somehow easily
# available on the target system.

# References: https://github.com/emacs-mirror/emacs

# shellcheck disable=2046
# disable for numbers instead of strings

# -----------------------------------------------------------------------------
# functions
# -----------------------------------------------------------------------------

clone_emacs() {
    # **
    # Clones GNU Emacs from repository
    # *

    printf 'Cloning and installing...\n'
    fast-git-clone -b 'master' 'https://github.com/emacs-mirror/emacs' '/tmp/emacs/'

    cd '/tmp/emacs/' || { err 'Cannot cd into dir.' && exit 1; }
}

# -----------------------------------------------------------------------------
# main
# -----------------------------------------------------------------------------

printf 'Installing dependencies...\n'
# Debian-like
if installed-p 'apt-get'; then
    # quit if non-root
    ! root-p && err 'This scripts needs root access.' && exit 1

    apt install -y \
        'autoconf' \
        'gnutls-dev' \
        'libgccjit-10-dev' \
        'libgif-dev' \
        'libgtk-3-dev' \
        'libjpeg-dev' \
        'libncurses-dev' \
        'libpng-dev' \
        'libtiff-dev' \
        'libxpm-dev' \
        'texinfo'

    clone_emacs
    ./autogen.sh
    ./configure --with-native-compilation
    
    make -j$(nproc)
    make -j$(nproc) install

elif installed-p 'pacman'; then
    clone_emacs
    ./autogen.sh
    ./configure
    
    make -j$(nproc)
    sudo make -j$(nproc) install
fi
