#!/bin/sh

# xinitrc --- Xorg setup

# Commentary:

# This file runs right after the X session started, mainly used to run
# the WM/DE.

# Code:

# shellcheck disable=SC1091

# load Xorg preamble
test -x "${XORGDIR:?}/xprofile" && . "${XORGDIR:?}/xprofile"

# -----------------------------------------------------------------------------
# window manager/desktop environment
# -----------------------------------------------------------------------------

# default
session=${1}

case ${session} in
dwm)
    # the following is for switching between local version of dwm* instead of
    # another default one (e.g: NixOS' directories)
    dwm_local_p=
    dwm=dwm
    dwmblocks=dwmblocks
    test "${dwm_local_p}" \
        && dwm='/usr/local/bin/dwm' && dwmblocks='/usr/local/bin/dwmblocks'

    # statusbar
    ${dwmblocks} &

    # run dwm as a loop for restarting, log it as well
    while :; do ${dwm} 2>"/tmp/dwm.log" >&2; done
    ;;
*)
    exec bspwm

    printf '\n\nError loading WM/DE\n' >&2
    exit 1
esac
