#!/bin/sh

# polylaunch --- <desc>

# Commentary:

# <desc>

# -----------------------------------------------------------------------------
# functions
# -----------------------------------------------------------------------------

runningp() {
    pidof -s "${1}" >/dev/null
}

launch() {
    {
        polybar -r "${1}" 2>&1
        printf '%s\n' '-------------------------------------------------------'
    } | tee -a "/tmp/polybar-${1}.log" >/dev/null
}

# -----------------------------------------------------------------------------
# main
# -----------------------------------------------------------------------------

# space separated list-alike of bars to display
bars='main'

# signal polybar to terminate, else do by force
runningp 'polybar' && {
    polybar-msg cmd quit || pkill -15 'polybar'
} >/dev/null

for b in ${bars}; do
    launch "${b}" & 
done
