#!/bin/sh

#   █████
#  ██░░░██
# ░██  ░░
# ░██   ██
# ░░█████
#  ░░░░░

# run with elevated privileges if not already
[ "$(id -u)" -ne 0 ] && exec sudo "$0" "$@"

# arch-based
[ -x "$(command -v "yay")" ] && {
    # compiler (alternatively tcc)
    yay --needed --noconfirm -Syy gcc

    ## ALE
    # fixer
    yay --needed --noconfirm -Syy uncrustify
}

# void
[ -x "$(command -v "xbps-install")" ] && {
    # compiler (alternatively tcc)
    xbps-install -Sy gcc

    ## ALE
    # fixer
    xbps-install -Sy uncrustify
}

# debian based
[ -x "$(command -v "apt")" ] && {
    # language server
    apt-get install -y clangd

    # [vim::ALE] (formatter)
    apt-get install -y uncrustify
}
