#!/bin/sh

#  ██                        ██              ██  ██
# ░██                       ░██             ░██ ░██
# ░██       ██████    ██████░██  ██  █████  ░██ ░██
# ░██████  ░░░░░░██  ██░░░░ ░██ ██  ██░░░██ ░██ ░██
# ░██░░░██  ███████ ░░█████ ░████  ░███████ ░██ ░██
# ░██  ░██ ██░░░░██  ░░░░░██░██░██ ░██░░░░  ░██ ░██
# ░██  ░██░░████████ ██████ ░██░░██░░██████ ███ ███
# ░░   ░░  ░░░░░░░░ ░░░░░░  ░░  ░░  ░░░░░░ ░░░ ░░░


# == generic install (distro-wide)
# install ghcup (GHC manager) (similar to rustup)
curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh

## ALE
# fixer
cabal install brittany
