#!/bin/sh

# debian-based
[ -x "$(command -v "apt")" ] && {
    # compiler
    sudo apt-get install haskell-platform haskell-stack -y

    ## ALE
    # linter
    sudo apt-get install hlint -y
}

## ALE
# fixer
sudo stack upgrade
stack install brittany
