#!/bin/sh

# compiler (using lts)
yay --needed --noconfirm -Syy \
    jdk11-openjdk \
    jre11-openjdk

# ide
#yay --needed --noconfirm -S intellij-idea-ce

# change environment
[ -x "$(command -v "pacman")" ] && {
    archlinux-java status
    sudo archlinux-java set java-11-openjdk
    archlinux-java status
}

## ALE
# linter (already installed (javac))

# fixer
yay --needed --noconfirm -Syy uncrustify
