#!/bin/sh

# arch-based
[ -x "$(command -v "yay")" ] && {
    # dependencies
    yay --needed --noconfirm -Syy nodejs

    ## ALE
    # fixer

    # FIXME: 'UNTESTED' [Sun, 19 Jul @ 19:04]
    yay --needed --noconfirm -Syy fixjson
}

# void
[ -x "$(command -v "xbps-install")" ] && {
    # dependencies
    sudo xbps-install -Sy nodejs

    ## ALE
    # fixer
    echo 'installing via npm...'
    sudo npm install -g fixjson
}
