#!/bin/sh

#     ██
#    ░░
#     ██  ██████  ██████  ███████
#    ░██ ██░░░░  ██░░░░██░░██░░░██
#    ░██░░█████ ░██   ░██ ░██  ░██
#  ██░██ ░░░░░██░██   ░██ ░██  ░██
# ░░███  ██████ ░░██████  ███  ░██
#  ░░░  ░░░░░░   ░░░░░░  ░░░   ░░

# -----------------------------------------------------------------------------
# preamble
# -----------------------------------------------------------------------------

# source utilities
# shellcheck disable=SC1090
. "$(dirname "$(dirname "$(readlink -f "$0")")")/utils"

# -----------------------------------------------------------------------------
# main
# -----------------------------------------------------------------------------

case $SYSTEM in
arch)
    # dependencies
    $PKG_INSTALL "nodejs"

    # [vim::ALE] (formatter)
    $PKG_INSTALL "fixjson"
    ;;

void)
    # elevate permissions
    elevate_perms "$@"

    # dependencies
    $PKG_INSTALL "nodejs"

    # [vim::ALE] (formatter)
    printf 'installing via npm...\n'
    npm install -g "fixjson"
    ;;
esac
