#!/bin/sh

# arch-based
[ -x "$(command -v "yay")" ] && {
    # dependencies
    yay --needed --noconfirm -Syy \
        nodejs \
        yarn

    ## ALE
    # fixer
    yay --needed --noconfirm -Syy prettier
}

# void
[ -x "$(command -v "xbps-install")" ] && {
    # dependencies
    sudo xbps-install -Sy \
        nodejs \
        yarn

    ## ALE
    # fixer
    echo 'installing via npm...'
    sudo npm install --global prettier
}
