#!/bin/sh

if [ -x "$(command -v "yay")" ]; then
    # dependencies
    yay --needed --noconfirm -Syy \
        nodejs \
        yarn

    ## ALE
    # fixer
    yay --needed --noconfirm -Syy prettier
fi
