#!/bin/sh

# arch-based
[ -x "$(command -v "yay")" ] && {
    ## dependencies
    yay --needed --noconfirm -Syy \
        python3 \
        python3-pip

}

# void
[ -x "$(command -v "xbps-install")" ] && {
    ## dependencies
    sudo xbps-install -Sy \
        python3 \
        python3-pip
}

## ALE
# linter
python3 -m pip install -U flake8

# fixer
python3 -m pip install -U black

## libs
python3 -m pip install -U \
    pylint \
    pynvim \
    rope \
    numpy \
    matplotlib \
    --user
