#!/bin/sh

#                     ██   ██
#  ██████   ██   ██  ░██  ░██
# ░██░░░██ ░░██ ██  ██████░██       ██████  ███████
# ░██  ░██  ░░███  ░░░██░ ░██████  ██░░░░██░░██░░░██
# ░██████    ░██     ░██  ░██░░░██░██   ░██ ░██  ░██
# ░██░░░     ██      ░██  ░██  ░██░██   ░██ ░██  ░██
# ░██       ██       ░░██ ░██  ░██░░██████  ███  ░██
# ░░       ░░         ░░  ░░   ░░  ░░░░░░  ░░░   ░░

# run with elevated privileges if not
[ "$(id -u)" -ne 0 ] && exec sudo "$0" "$@"

# arch-based
[ -x "$(command -v "yay")" ] && {
    ## dependencies
    yay --needed --noconfirm -Syy \
        python3 \
        python3-pip
}

# void
[ -x "$(command -v "xbps-install")" ] && {
    ## dependencies
    xbps-install -Sy \
        python3 \
        python3-pip
}

# debian-based
[ -x "$(command -v "apt")" ] && {
    ## dependencies
    apt-get install -y \
        python3 \
        python3-pip
}

# language server
python3 -m pip install -U setuptools python-language-server

# [vim::ALE] (fixer)
python3 -m pip install -U black

## libs
python3 -m pip install -U \
    pylint \
    pynvim \
    rope \
    numpy \
    matplotlib \
    --user
