#!/bin/sh

## dependencies
yay --needed --noconfirm -S \
    python3 \
    python-pip

## ALE
# linter
python3 -m pip install -U flake8

# fixer
python3 -m pip install -U black

## libs
python3 -m pip install -U \
    pylint \
    rope \
    numpy \
    matplotlib \
    --user
