#!/bin/sh

# arch-based
[ -x "$(command -v "yay")" ] && {
    # compiler (cargo, cargo-nightly, rust, rustfmt, rust-nightly)
    yay --needed --noconfirm -Syy rustup
}

# void
[ -x "$(command -v "xbps-install")" ] && {
    # compiler (cargo, cargo-nightly, rust, rustfmt, rust-nightly)
    sudo xbps-install -Sy rustup
}

# rustup
rustup toolchain install stable || exit 1
rustup default stable || exit 1
rustup component add rls rust-analysis rust-src || exit 1
rustup update || exit 1
