#!/bin/sh

#                           ██
#                          ░██
#  ██████ ██   ██  ██████ ██████
# ░░██░░█░██  ░██ ██░░░░ ░░░██░
#  ░██ ░ ░██  ░██░░█████   ░██
#  ░██   ░██  ░██ ░░░░░██  ░██
# ░███   ░░██████ ██████   ░░██
# ░░░     ░░░░░░ ░░░░░░     ░░

# -----------------------------------------------------------------------------
# preamble
# -----------------------------------------------------------------------------

# source utilities
# shellcheck disable=SC1090
. "$(dirname "$(dirname "$(readlink -f "$0")")")/utils"

# -----------------------------------------------------------------------------
# main
# -----------------------------------------------------------------------------

case $SYSTEM in
arch)
    # compiler (rust, cargo, rustfmt)
    $PKG_INSTALL "rustup"
    ;;

void)
    # elevate permissions
    elevate_perms "$@"

    # compiler (rust, cargo, rustfmt)
    $PKG_INSTALL "rustup"
    ;;
esac

# == post-install
rustup update
rustup toolchain install stable
rustup default stable
rustup component add rls rust-analysis rust-src
rustup update
