#!/bin/sh

# void
if [ -x "$(command -v "xbps-install")" ]; then
    # pre-requisites
    sudo xbps-install -Sy linux-headers

    # virtualbox
    sudo xbps-install -Sy virtualbox-ose

    # load modules
    sudo modules-load

    # force reconfiguration in case of failure
    sudo xbps-reconfigure -f virtualbox-ose-dkms
fi

#******************************************************************************
# sources
#******************************************************************************

# https://0x0.st/XbXL (deprecated)
