#!/bin/sh

#          ██
#         ░██
#   ██████░██
#  ██░░░░ ░██████
# ░░█████ ░██░░░██
#  ░░░░░██░██  ░██
#  ██████ ░██  ░██
# ░░░░░░  ░░   ░░

# run with elevated privileges if not
[ "$(id -u)" -ne 0 ] && exec sudo "$0" "$@"

# arch-based
[ -x "$(command -v "yay")" ] && {
    ## ALE
    # linter
    yay --needed --noconfirm -Syy shellcheck
    # fixer
    yay --needed --noconfirm -Syy shfmt
}

# void
[ -x "$(command -v "xbps-install")" ] && {
    ## ALE
    # linter
    xbps-install -Sy shellcheck
    # fixed
    xbps-install -Sy shfmt
}

# debian-based
[ -x "$(command -v "apt")" ] && {
    # [vim::ALE] (formatter)
    apt-get install shellcheck -y
}
