#!/bin/sh

# arch-based
[ -x "$(command -v "yay")" ] && {
    ## ALE
    # linter
    yay --needed --noconfirm -Syy shellcheck
    # fixer
    yay --needed --noconfirm -Syy shfmt
}

# void
[ -x "$(command -v "xbps-install")" ] && {
    ## ALE
    # linter
    sudo xbps-install -Sy shellcheck
    # fixed
    sudo xbps-install -Sy shfmt
}
