#!/bin/sh

# arch
if [ -x "$(command -v "yay")" ]; then
    # compiler
    yay --needed --noconfirm -S \
        biber \
        pandoc \
        pandoc-citeproc \
        texlive-most

# void
elif [ -x "$(command -v "xbps-install")" ]; then
    # compiler
    sudo xbps-install -Sy \
        biber \
        pandoc \
        texlive-bin

    # tlmgr
    # gnupg is required to install via tlmgr
    sudo xbps-install -Sy gnupg
    sudo tlmgr install biblatex
    sudo tlmgr install biber
    sudo tlmgr install biblatex-apa
    # update
    sudo tlmgr update --all
    sudo texhash
fi

#******************************************************************************
# references
#******************************************************************************

# https://0x0.st/XmyQ
