#!/bin/sh

#    ██
#   ░██
#  ██████  █████  ██   ██
# ░░░██░  ██░░░██░░██ ██
#   ░██  ░███████ ░░███
#   ░██  ░██░░░░   ██░██
#   ░░██ ░░██████ ██ ░░██
#    ░░   ░░░░░░ ░░   ░░

# -----------------------------------------------------------------------------
# preamble
# -----------------------------------------------------------------------------

# source utilities
# shellcheck disable=SC1090
. "$(dirname "$(dirname "$(readlink -f "$0")")")/utils"

# -----------------------------------------------------------------------------
# main
# -----------------------------------------------------------------------------

case $SYSTEM in
arch)
    # compiler & tools
    $PKG_INSTALL "texlive-most" "biber" "pandoc" "pandoc-citeproc"
    ;;

void)
    # elevate permissions
    elevate_perms "$@"

    # compiler & tools
    $PKG_INSTALL "texlive-bin" "biber" "pandoc"

    # == tlmgr
    # gnupg is required to install via tlmgr
    $PKG_INSTALL "gnupg"

    # update
    tlmgr update --all

    tlmgr install biblatex
    tlmgr install biblatex-apa
    tlmgr install biblatex-ieee
    tlmgr install capt-of
    tlmgr install wrapfig

    # cleanup
    tlmgr update --all
    texhash
    ;;
esac

# -----------------------------------------------------------------------------
# references
# -----------------------------------------------------------------------------

# https://0x0.st/XmyQ
