#!/bin/sh

# arch-based
[ -x "$(command -v "yay")" ] && {
    # compiler
    yay --needed --noconfirm -S \
        biber \
        pandoc \
        pandoc-citeproc \
        texlive-most
}

# void
[ -x "$(command -v "xbps-install")" ] && {
    # compiler
    sudo xbps-install -Sy \
        biber \
        pandoc \
        texlive-bin

    # tlmgr
    # gnupg is required to install via tlmgr
    sudo xbps-install -Sy gnupg
    #sudo tlmgr install biber
    sudo tlmgr install biblatex
    sudo tlmgr install biblatex-apa
    sudo tlmgr install biblatex-ieee
    # update
    sudo tlmgr update --all
    sudo texhash
}

#******************************************************************************
# references
#******************************************************************************

# https://0x0.st/XmyQ
