#!/bin/sh

# -----------------------------------------------------------------------------
# preamble
# -----------------------------------------------------------------------------

# source utilities
# shellcheck disable=SC1090
. "$LIBSHUTILS/sys-utils"

# -----------------------------------------------------------------------------
# main
# -----------------------------------------------------------------------------

case $SYSTEM in
void)
    # check if running with elevated priviledges; elevate if not
    ! is_su && elevate_privs "$0" "$@"

    # pkgs
    $PKG_INSTALL "virtualbox-ose"

    # load modules
    modules-load

    # force reconfig just in case
    xbps-reconfigure -f "virtualbox-ose-dkms"
    ;;
esac

# after
printf '\n...it is recommended to reboot system\n'
