#!/bin/sh

# -----------------------------------------------------------------------------
# preamble
# -----------------------------------------------------------------------------

# source utilities
# shellcheck disable=SC1090
. "${LIBSHUTILS:?}/sys-utils"

# -----------------------------------------------------------------------------
# main
# -----------------------------------------------------------------------------

case ${SYSTEM:?} in
arch)
        # check if running with elevated priviledges; elevate if not
        ! is_su && elevate_privs "$0" "$@"

        # pkgs
        ${PKG_INSTALL:?} 'virtualbox'

        # LTS install
        if is_installed 'linux-lts'; then
        ${PKG_REMOVE:?} 'virtualbox-host-modules-arch'
                ${PKG_INSTALL:?} 'linux-lts-headers' 'virtualbox-host-dkms'

        # default install
        else
            ${PKG_REMOVE:?} 'virtualbox-host-dkms'
            ${PKG_INSTALL:?} 'virtualbox-host-modules-arch'
        fi

        # load the virtualbox kernel modules
        modprobe vboxdrv

        ;;

void)
        # check if running with elevated priviledges; elevate if not
        ! is_su && elevate_privs "$0" "$@"

        # pkgs
        ${PKG_INSTALL:?} 'virtualbox-ose'

        # load modules
        modules-load

        # force reconfig (just in case)
        xbps-reconfigure -f 'virtualbox-ose-dkms'
        ;;

*) die 'no settings setup for current environment' ;;
esac

# after
printf '\n...it is recommended to reboot system\n'
