#!/bin/sh

vs_install() {
    if [ -x "$(command -v "codium")" ]; then
        codium --install-extension "$1"
    elif [ -x "$(command -v "code-oss")" ]; then
        code-oss --install-extension "$1"
    fi
}

# general
vs_install eamodio.gitlens
# vs_install formulahendry.code-runner
vs_install visualstudioexptteam.vscodeintellicode

# visual
vs_install teabyii.ayu
# vs_install dracula-theme.theme-dracula
vs_install robbowen.synthwave-vscode

# java
vs_install redhat.java
vs_install vscjava.vscode-java-debug
vs_install vscjava.vscode-java-dependency
vs_install vscjava.vscode-java-pack
vs_install vscjava.vscode-java-test

# shell
# vs_install foxundermoon.shell-format

# markdown
# vs_install yzhang.markdown-all-in-one
# vs_install davidanson.vscode-markdownlint

# python
# vs_install ms-python.python

# uncrustify (formatter/fixer)
vs_install laurenttreguier.uncrustify

# spell
vs_install streetsidesoftware.code-spell-checker
vs_install streetsidesoftware.code-spell-checker-spanish
