#!/bin/sh

install_vscext() {
    [ -x "$(command -v "codium")" ] && [ ! -x "$(command -v "code-oss")" ] &&
        [ ! -x "$(command -v "code")" ] && codium --install-extension "$1"
    [ -x "$(command -v "code-oss")" ] && [ ! -x "$(command -v "codium")" ] &&
        [ ! -x "$(command -v "code")" ] && code-oss --install-extension "$1"
    [ -x "$(command -v "code")" ] && [ ! -x "$(command -v "codium")" ] &&
        [ ! -x "$(command -v "code-oss")" ] && code --install-extension "$1"
}

# -----------------------------------------------------------------------------
# general
# -----------------------------------------------------------------------------
# intellisense for various languages
install_vscext "VisualStudioExptTeam.vscodeintellicode"

# Code Runner
install_vscext "formulahendry.code-runner"

# vi key-binds
install_vscext "vscodevim.vim"

# GitLens (visual git)
install_vscext "eamodio.gitlens"

# -----------------------------------------------------------------------------
# appearance
# -----------------------------------------------------------------------------
# themes & icons
install_vscext "teabyii.ayu"
install_vscext "robertrossmann.remedy"
install_vscext "fooxly.themeswitch"

# -----------------------------------------------------------------------------
# Shell
# -----------------------------------------------------------------------------
install_vscext "timonwong.shellcheck"

# -----------------------------------------------------------------------------
# C/C++
# -----------------------------------------------------------------------------
install_vscext "ms-vscode.cpptools"

# -----------------------------------------------------------------------------
# Java
# -----------------------------------------------------------------------------
install_vscext "vscjava.vscode-java-pack"

# -----------------------------------------------------------------------------
# Markdown
# -----------------------------------------------------------------------------
install_vscext "yzhang.markdown-all-in-one"
install_vscext "davidanson.vscode-markdownlint"

# -----------------------------------------------------------------------------
# formatting
# -----------------------------------------------------------------------------
# uncrustify (formatter/fixer)
install_vscext "laurenttreguier.uncrustify"

# -----------------------------------------------------------------------------
# spell checking
# -----------------------------------------------------------------------------
install_vscext "streetsidesoftware.code-spell-checker"
install_vscext "streetsidesoftware.code-spell-checker-spanish"