---

- name: Link cfgs
  ansible.builtin.file:
    src: "{{ role_path }}/files/.config/xorg/"
    dest: "{{ cfg_dir }}/xorg"
    state: link

- name: Link XDG-user cfgs
  ansible.builtin.file:
    src: "{{ role_path }}/files/.config/user-dirs.dirs"
    dest: "{{ cfg_dir }}/user-dirs.dirs"
    state: link

- name: Link mime-apps cfgs
  ansible.builtin.file:
    src: "{{ role_path }}/files/.config/mimeapps.list"
    dest: "{{ cfg_dir }}/mimeapps.list"
    force: yes
    state: link

- name: Link share/application cfgs
  ansible.builtin.file:
    src: "{{ role_path }}/files/.config/applications/"
    dest: "{{ local_dir }}/share/applications"
    state: link

- name: Ensure '/etc/X11/xorg.conf.d/' dir exists
  file: path='/etc/X11/xorg.conf.d/' state=directory

- name: Link Xorg cfg
  become: true
  ansible.builtin.file:
    src: "{{ role_path }}/files/xorg.conf.d/50-mouse-acceleration.conf"
    dest: '/etc/X11/xorg.conf.d/50-mouse-acceleration.conf'
    state: link
