#!/bin/sh

#  ██                        ██              ██  ██
# ░██                       ░██             ░██ ░██
# ░██       ██████    ██████░██  ██  █████  ░██ ░██
# ░██████  ░░░░░░██  ██░░░░ ░██ ██  ██░░░██ ░██ ░██
# ░██░░░██  ███████ ░░█████ ░████  ░███████ ░██ ░██
# ░██  ░██ ██░░░░██  ░░░░░██░██░██ ░██░░░░  ░██ ░██
# ░██  ░██░░████████ ██████ ░██░░██░░██████ ███ ███
# ░░   ░░  ░░░░░░░░ ░░░░░░  ░░  ░░  ░░░░░░ ░░░ ░░░

# -----------------------------------------------------------------------------
# preamble
# -----------------------------------------------------------------------------

# source utilities
# shellcheck disable=SC1090
. "$LIBSHUTILS/sys-utils"

# -----------------------------------------------------------------------------
# main
# -----------------------------------------------------------------------------

# quit if already installed
[ -d "$HOME/.ghcup" ] && {
    printf 'ghcup is already installed @ %s/.ghcup\n' "$HOME"
    exit 1
}

case $SYSTEM in
*)
    # install ghcup (GHC manager) (similar to rustup)
    curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh

    # update Cabal (Haskell's package manager)
    "$HOME/.ghcup/bin/cabal" update

    # [vim::ALE] (formatter)
    "$HOME/.ghcup/bin/cabal" install brittany
    ;;
esac
