#!/bin/sh

#     ██
#    ░░
#     ██  ██████  ██████  ███████
#    ░██ ██░░░░  ██░░░░██░░██░░░██
#    ░██░░█████ ░██   ░██ ░██  ░██
#  ██░██ ░░░░░██░██   ░██ ░██  ░██
# ░░███  ██████ ░░██████  ███  ░██
#  ░░░  ░░░░░░   ░░░░░░  ░░░   ░░

# -----------------------------------------------------------------------------
# preamble
# -----------------------------------------------------------------------------

# source utilities
# shellcheck disable=SC1090
. "$LIBSHUTILS/sys-utils"

# -----------------------------------------------------------------------------
# main
# -----------------------------------------------------------------------------

case $SYSTEM in
arch)
    # dependencies
    $PKG_INSTALL "nodejs"

    # [vim::ALE] (formatter)
    $PKG_INSTALL "fixjson"
    ;;

void)
    # check if running with elevated priviledges; elevate if not
    ! is_su && elevate_privs "$0" "$@"

    # dependencies
    $PKG_INSTALL "nodejs"

    # [vim::ALE] (formatter)
    printf 'installing via npm...\n'
    npm install -g "fixjson"
    ;;
esac
