#!/bin/sh

#                     ██   ██
#  ██████   ██   ██  ░██  ░██
# ░██░░░██ ░░██ ██  ██████░██       ██████  ███████
# ░██  ░██  ░░███  ░░░██░ ░██████  ██░░░░██░░██░░░██
# ░██████    ░██     ░██  ░██░░░██░██   ░██ ░██  ░██
# ░██░░░     ██      ░██  ░██  ░██░██   ░██ ░██  ░██
# ░██       ██       ░░██ ░██  ░██░░██████  ███  ░██
# ░░       ░░         ░░  ░░   ░░  ░░░░░░  ░░░   ░░

# -----------------------------------------------------------------------------
# preamble
# -----------------------------------------------------------------------------

# source utilities
# shellcheck disable=SC1090
. "$LIBSHUTILS/sys-utils"

# -----------------------------------------------------------------------------
# main
# -----------------------------------------------------------------------------

case $SYSTEM in
arch)
    # tools
    $PKG_INSTALL "python3" "python-pip"
    ;;

void)
    # check if running with elevated priviledges; elevate if not
    ! is_su && elevate_privs "$0" "$@"

    # tools
    $PKG_INSTALL "python3" "python3-pip"
    ;;

debian)
    # check if running with elevated priviledges; elevate if not
    ! is_su && elevate_privs "$0" "$@"

    # tools
    $PKG_INSTALL "python3" "python3-pip"
    ;;
esac

# == post-install
# dependencies
python3 -m pip install -U "setuptools"
python3 -m pip install -U "pip"

# language server
python3 -m pip install -U "python-language-server"

# code formatter (preferred over autopep8 & YAPF)
python3 -m pip install -U "black"

# libs
python3 -m pip install -U \
    "numpy" \
    "pynvim" \
    "rope"
