#!/bin/sh

# emacs-setup --- Emacs from source setup

# Commentary:

# Installs GNU Emacs from source.
# Optionally build with native compilation if `libgccjit` is somehow easily
# available on the target system.

# References: https://github.com/emacs-mirror/emacs

# Code:

# checks
! rootp && err 'This scripts needs root access' && exit 1

# -----------------------------------------------------------------------------
# variables
# -----------------------------------------------------------------------------

branch='master'

# debug ./configure options before installing
debug_configure=

# -----------------------------------------------------------------------------
# flags
# -----------------------------------------------------------------------------

# generic flags
flags="--with-native-compilation \
--with-mailutils \
--with-sound=yes \
--without-compress-install"

# g-stuff
flags="${flags} --without-gsettings \
--without-gconf"

# shaping-text related stuff
# disabling the following forces the use Harfbuzz
flags="${flags} --with-harfbuzz \
--without-libotf \
--without-m17n-flt"

# windowing system
flags="${flags} --with-x-toolkit=gtk3 \
--with-xwidgets \
--without-xaw3d"

# -----------------------------------------------------------------------------
# functions
# -----------------------------------------------------------------------------

clone_emacs() {
    # **
    # Clones GNU Emacs from repository.
    # *

    printf 'Cloning Emacs repository...\n'
    git-clone-fast-b "${branch}" 'https://github.com/emacs-mirror/emacs' '/tmp/emacs/'

    cd '/tmp/emacs/' || { err 'Cannot cd into dir.' && exit 1; }
}

configure() {
    # **
    # Configures GNU Emacs autoconf settings.
    # *

    ./autogen.sh
    ./configure ${flags}

    # debug
    if test ! -z "${debug_configure}"; then
        printf 'Debug is enabled, quitting...\n'
        exit 0
    fi

    printf '\n--------------------------------------------------------------\n'
    printf 'Resuming in 10 seconds...\n'
    printf 'Please review the settings shown above and check for errors.\n'
    printf '--------------------------------------------------------------\n'
    sleep 10
}

install() {
    # **
    # Install GNU Emacs to the system.
    # *

    # shellcheck disable=2046
    # these are numbers
    make -j`nproc`
    make -j`nproc` install
}

dependencies() {
    printf 'Installing dependencies...\n'

    # Debian-like
    if installedp 'apt-get'; then
        apt install -y         \
            'autoconf'         \
            'gnutls-dev'       \
            'libgccjit-10-dev' \
            'libgif-dev'       \
            'libgtk-3-dev'     \
            'libjpeg-dev'      \
            'libncurses-dev'   \
            'libpng-dev'       \
            'libtiff-dev'      \
            'libxpm-dev'       \
            'texinfo'
    elif installedp 'pacman'; then
        pacman --needed --noconfirm -Syu \
               'base-devel'              \
               'libgccjit'               \
               'webkit2gtk'
    fi
}

# -----------------------------------------------------------------------------
# main
# -----------------------------------------------------------------------------

dependencies
clone_emacs
configure
install
