#!/bin/sh

# nix-setup --- Nix Package Manager setup

# Commentary:

# This installation script is distro-agnostic.

# References: https://nixos.org/manual/nix/stable/

# Code:

# only download & install if '/nix/' folder is absent
test ! -d '/nix/' && {
    curl -L 'https://nixos.org/nix/install' | sh
} || {
    printf "'/nix/' is present, Nix is probably installed already\n" >/dev/null 2>&1
    exit 1
}
