#!/bin/sh
#
# rust-toolchain-install.sh --- Installs the Rust programming language toolchain
#
#
# Code:

# Define global variables
DEFAULT_TOOLCHAIN='stable'
PROFILE='default'

curl --proto '=https' --tlsv1.2 -Sfs 'https://sh.rustup.rs' \
    | sh -s -- \
    -q -y --default-toolchain ${DEFAULT_TOOLCHAIN} --profile ${PROFILE} --no-modify-path \
    --component 'rust-src' 'rust-analyzer'

# install binaries via cargo
cargo install --locked 'cargo-binstall'

# helps compilation time
cargo binstall --no-confirm --locked 'sccache'

exit 0

