#!/bin/sh

# woeusb-setup --- Downloads WoeUSB utility.

# Commentary:

# This program allows flashing Windows images.

git_repo='https://github.com/WoeUSB/WoeUSB/'
save_dir="${HOME}/lib/"

# dependencies
printf 'Installing dependencies...\n'

# arch-based
if installedp 'pacman'; then
    sudo pacman --needed --noconfirm -Syu 'parted' 'wimlib'
fi

printf 'Dependencies have been installed...\n'

# checks
test -r "${save_dir}/woeusb" \
    && err "WoeUSB is already downloaded at '${save_dir}'." \
    && exit 1

git-clone-fast "${git_repo}" '/tmp/woeusb/'

cp '/tmp/woeusb/sbin/woeusb' "${save_dir}"

printf "WoeUSB has been downloaded to '%s'\n" "${save_dir}."
