#!/bin/sh

# -----------------------------------------------------------------------------
# preamble
# -----------------------------------------------------------------------------

# source utilities
# shellcheck disable=SC1090
. "$(dirname "$(dirname "$(readlink -f "$0")")")/utils"

# -----------------------------------------------------------------------------
# main
# -----------------------------------------------------------------------------

case $SYSTEM in
arch)
    # quit if multilib repo is disabled
    grep -q "^#\[multilib\]$" "/etc/pacman.conf" && {
        printf 'multilib repo is disabled, enable it @ /etc/pacman.conf\n'
        exit 1
    }

    # lutris
    $PKG_INSTALL "lutris"

    # steam
    $PKG_INSTALL "steam"

    # wine
    $PKG_INSTALL "wine" "wine-gecko" "wine-mono"
    ;;
esac
