#!/bin/sh

# **
# script for installing games/launchers/etc
#
# note: this script depends heavily on hardware-specific packages
# *

# -----------------------------------------------------------------------------
# preamble
# -----------------------------------------------------------------------------

# source utilities
# shellcheck disable=SC1090
. "${LIBSHUTILS:?}/sys-utils"

# -----------------------------------------------------------------------------
# main
# -----------------------------------------------------------------------------

case ${SYSTEM:?} in
arch)
    # quit if multilib repo is disabled
    grep -q "^#\[multilib\]$" '/etc/pacman.conf' && {
        printf 'multilib repo is disabled, enable it @ /etc/pacman.conf\n'
        exit 1
    }

    # lutris
    ${PKG_INSTALL:?} 'lutris'

    # steam
    ${PKG_INSTALL:?} 'steam'

    # wine
    ${PKG_INSTALL:?} 'wine' 'wine-gecko' 'wine-mono'
    ;;

void)
    # check if running with elevated priviledges; elevate if not
    ! is_su && elevate_privs "$0" "$@"

    # install extra repos if not already
    ! xbps-query "void-repo-multilib" >/dev/null 2>&1 && {
        ${PKG_INSTALL:?} \
            'void-repo-nonfree' \
            'void-repo-multilib' \
            'void-repo-multilib-nonfree'
    }

    # lutris
    ${PKG_INSTALL:?} 'lutris'

    # wine
    ${PKG_INSTALL:?} 'wine' 'wine-gecko' 'wine-mono'
    ;;

*) die 'no settings setup for current environment' ;;
esac
