#!/bin/sh

# **
# script for installing a VPN client
#
# *

# -----------------------------------------------------------------------------
# preamble
# -----------------------------------------------------------------------------

# source utilities
# shellcheck disable=SC1090
. "${LIBSHUTILS:?}/sys-utils"

# -----------------------------------------------------------------------------
# main
# -----------------------------------------------------------------------------

case ${SYSTEM:?} in
arch)
    # dependencies
    ${PKG_INSTALL:?} 'openvpn' 'dialog' 'python-pip' 'python-setuptools'
    ;;

*) die 'no settings setup for current environment' ;;
esac

# check if running with elevated priviledges; elevate if not
! is_su && elevate_privs "$0" "$@"

pip3 install -U 'protonvpn-cli'
