#!/bin/sh

# install-quicklisp --- Quicklisp installer script

test -d "${HOME}/quicklisp/" && exit 0

ql_install_dir='/tmp/quicklisp.lisp'

wget -q -O "${ql_install_dir}" 'https://beta.quicklisp.org/quicklisp.lisp'
sbcl --non-interactive --load "${ql_install_dir}" --eval '(quicklisp-quickstart:install)'
