#!/bin/sh
set -eu

nix_sh=/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
swapfile=/var/swapfile

cleanup() {
    sudo rm -f "${swapfile}.new"
}
trap cleanup EXIT
for sig in HUP INT TERM; do
    # shellcheck disable=SC2064
    trap "trap '' HUP INT TERM; cleanup; trap - EXIT ${sig}; kill -s ${sig} \$\$" "${sig}"
done

if [ ! -f "${swapfile}" ]; then
    sudo fallocate -l 4G "${swapfile}.new"
    sudo chmod 600 "${swapfile}.new"
    sudo /sbin/mkswap "${swapfile}.new" >/dev/null
    sudo mv "${swapfile}.new" "${swapfile}"
fi
.agents/resume

if [ ! -e "${nix_sh}" ]; then
    bin/nix-install.sh \
        --extra-conf "extra-substituters = https://anntnzrb.cachix.org" \
        --extra-conf "extra-trusted-public-keys = anntnzrb.cachix.org-1:hG29RyjX45a9q1nZqdvOJUQ6nRDG/Jj4yt2d1dpWCgE="
fi

marker='# amp orb: nix'
if ! grep -qF "${marker}" "${HOME}/.bash_profile" 2>/dev/null; then
    cat >>"${HOME}/.bash_profile" <<PROFILE

${marker}
unset __ETC_PROFILE_NIX_SOURCED
. ${nix_sh}
if [ -z "\${IN_NIX_SHELL:-}" ] && [ -f "\${PWD}/flake.nix" ]; then
    eval "\$(nix print-dev-env "\${PWD}")"
fi
PROFILE
fi

unset __ETC_PROFILE_NIX_SOURCED
# shellcheck disable=SC1090
. "${nix_sh}"
nix print-dev-env . >/dev/null
