#!/bin/sh

# shellcheck disable=1090,1091
# bypass non-constant source following

#          ██          ██   ██
#         ░░          ░░   ░██
#  ██   ██ ██ ███████  ██ ██████
# ░░██ ██ ░██░░██░░░██░██░░░██░
#  ░░███  ░██ ░██  ░██░██  ░██
#   ██░██ ░██ ░██  ░██░██  ░██
#  ██ ░░██░██ ███  ░██░██  ░░██
# ░░   ░░ ░░ ░░░   ░░ ░░    ░░
# runs after executing `startx`

# load defaults
xinit_cfg_dir='/etc/X11/xinit/xinitrc.d'
test -d "${xinit_cfg_dir}" && {
    for f in "${xinit_cfg_dir}"/*.sh ; do
        test -x "${f}" && . "${f}"
    done
    unset f
}
unset -v xinit_cfg_dir

# -----------------------------------------------------------------------------
# Xorg settings
# -----------------------------------------------------------------------------

xrandr --dpi 92 &   # DPI defaulted to 1920x1080 24" screen
xset s off &        # disable screensaver
xset dpms 0 0 900 & # off-screen time
# source Xresources and ensure it's loaded before running WM/DE
xrdb "${XORGDIR}/xorg/Xresources" & xrdbflag=1
test -n "${xrdbflag}" && wait "${xrdbflag}" && unset -v xrdbflag

# load X start-up programs
test -x "${XORGDIR}/xprofile" && . "${XORGDIR}/xprofile"

# -----------------------------------------------------------------------------
# graphical environment (window manager/desktop environment)
# -----------------------------------------------------------------------------

# default ses
session=${1:-awesome}

case ${session} in
i3)
    unset -v session

    exec i3
    ;;

awesome)
    unset -v session

    exec awesome
    ;;

dwm)
    unset -v session

    # statusbar
    dwmblocks &

    # run dwm as a loop for restarting, log it as well
    while :; do dwm 2>"/tmp/dwm.log" >&2; done
    ;;
*)
    unset -v session
    exec ${1}

    printf "\n\nerror :: '%s'\n" "$1" >&2
    exit 1
esac
