#!/bin/sh

# sh-aliases --- Aliases for the shell.

# Commentary:

# This aliases are shell-agnostic with portability in mind.

# References:
# - https://wiki.archlinux.org/title/Core_utilities

# shellcheck disable=2006
# keep backticks for portability.

# = core utilities

# ls === exa
if test -x "`command -v 'exa'`"; then
    alias \
        ls='exa --color=automatic --group-directories-first --icons --sort=Name -Fagh' \
        ll='exa --color=automatic --group-directories-first --icons --sort=Name -Faglh'
else
    alias \
        ls='ls --color=auto --group-directories-first -AFhq'  \
        ll='ls --color=auto --group-directories-first -AFhlq'
fi

# cat/less === bat
if test -x "`command -v 'bat'`"; then
    alias \
        cat='bat --color=auto --theme="Monokai Extended Origin" --style=full -P' \
        less='bat --color=auto --theme="Monokai Extended Origin" --style=full'
else
    alias cat='cat -n'
fi

alias \
    cp='cp -Riv'                     \
    diff='diff --color=auto'         \
    grep='grep --color=auto -in'    \
    mkdir='mkdir -pv'                \
    lsblk='lsblk -ap'                \
    mv='mv -iv'                      \
    rm='rm -v'                       \
    rmfr='rm -Rfv'                   \
    tree='tree --dirsfirst -CFlq '   \
    treea='tree --dirsfirst -CFalq '   \
    treed='tree --dirsfirst -CFdlq ' \
    zip='zip -rv'

# shortcuts
alias \
    eed='${EDITOR:?}'              \
    seed='sudo ${EDITOR:?}'        \
    sx11='startx ${HOME}/.config/xorg/xinitrc' \
    kx11="pkill -15 'X'"

# -----------------------------------------------------------------------------
# miscellaneous
# -----------------------------------------------------------------------------

alias \
    ascii="toilet -t -f '3d'"                                                      \
    tnet="ping 'example.com'"                                                      \
    tnetspeed='speedtest-cli'                                                      \
    yt='yt-dlp --restrict-filenames'                                           \
    ytf='yt-dlp -F'                                                            \
    ytt='yt-dlp --restrict-filenames --skip-download --write-thumbnail'        \
    yta="yt-dlp --restrict-filenames --prefer-ffmpeg --audio-format 'best' -x" \
    ytv="yt-dlp --restrict-filenames -f 'best'"
