#!/usr/bin/env zsh

ICO_DIRTY=" ❌"
ICO_AHEAD=" ↑"
ICO_BEHIND=" ↓"
ICO_DIVERGED=" ↕"

COLOR_ROOT="%F{red}"
COLOR_USER="%F{cyan}"
COLOR_NORMAL="%F{white}"
PROMPT_STYLE="classic"

# enable functions in the prompt
setopt PROMPT_SUBST

# colors for permissions
if [[ "$EUID" -ne "0" ]]; then # if user is not root
    USER_LEVEL="${COLOR_USER}"
else # root!
    USER_LEVEL="${COLOR_ROOT}"
fi

# git prompt
GIT_PROMPT() {
    test=$(git rev-parse --is-inside-work-tree 2>/dev/null)
    if [ ! "$test" ]; then
        case "$PROMPT_STYLE" in
        ascii)
            echo "$reset_color%F{cyan}▒░"
            ;;
        arrows)
            echo "$reset_color%F{cyan}"
            ;;
        esac
        return
    fi

    ref=$(git name-rev --name-only HEAD | sed 's!remotes/!!;s!undefined!merging!' 2>/dev/null)
    dirty="" && [[ $(git diff --shortstat 2>/dev/null | tail -n1) != "" ]] && dirty=$ICO_DIRTY
    stat=$(git status | sed -n 2p)
    case "$stat" in
    *ahead*)
        stat=$ICO_AHEAD
        ;;
    *behind*)
        stat=$ICO_BEHIND
        ;;
    *diverged*)
        stat=$ICO_DIVERGED
        ;;
    *)
        stat=""
        ;;
    esac

    echo "${USER_LEVEL}━[${COLOR_NORMAL}"${ref}${dirty}${stat}"${USER_LEVEL}]"
}
PROMPT='${USER_LEVEL}║ ${COLOR_NORMAL}%~${USER_LEVEL} ║$(GIT_PROMPT) ◞◜·◦° %f'
