#!/bin/sh

#                                       ████ ██  ██
#             ██████                   ░██░ ░░  ░██
#     ██   ██░██░░░██ ██████  ██████  ██████ ██ ░██  █████
#    ░░██ ██ ░██  ░██░░██░░█ ██░░░░██░░░██░ ░██ ░██ ██░░░██
#     ░░███  ░██████  ░██ ░ ░██   ░██  ░██  ░██ ░██░███████
#  ██  ██░██ ░██░░░   ░██   ░██   ░██  ░██  ░██ ░██░██░░░░
# ░██ ██ ░░██░██     ░███   ░░██████   ░██  ░██ ███░░██████
# ░░ ░░   ░░ ░░      ░░░     ░░░░░░    ░░   ░░ ░░░  ░░░░░░
# ░░░░ runs on tty / dm login

# personal keyboard settings
remaps &

# sets the background with `setbg` script
setbg &

# compositor
picom -b &

# global keybindings
sxhkd -m 1 -t 2 -a 'Escape' -c "${HOME}/.config/sxhkd/sxhkdrc" &

# dunst
dunst &

# hide mouse when idle
unclutter -grab &

# light filter
redshift -l \
         "$(curl -Ss \
         https://location.services.mozilla.com/v1/geolocate?key=geoclue \
         | awk 'OFS=":" { print $3,$5 }' | tr -d ',}')" &

# system monitor
"${TERMINAL:?}" -e 'htop' &

# applets (requires a bar which supports them)
# NetworkManager
nm-applet &
pasystray &

# dmenu display select prompt (wait a bit for prompt)
{ sleep 5 && displayselect; } &
