#+TITLE: sxhkd
#+PROPERTY: header-args :comments org :results silent

* table of contents                                       :TOC_2_gh:noexport:
- [[#overview][overview]]
- [[#keybinds][keybinds]]
  - [[#applications][applications]]
  - [[#controls][controls]]
  - [[#tools][tools]]
- [[#reload-configuration][reload configuration]]

* overview
[[https://github.com/baskerville/sxhkd][sxhdk]] is a hotkey daemon for /X/. having my keybinds isolated from my window
manager allow me to transition between graphical environments without
configuring them individually on each of them. this program allows me to make
them portable.

* keybinds

** applications

*** terminal emulator

set by =$TERMINAL= environment variable
#+begin_src sh :tangle sxhkdrc
super + Return
  $TERMINAL
#+end_src

*** text editor

/text editor/, but just as a generic way to call it. this is a terminal-based
text editor, set by =$EDITOR= variable
#+begin_src sh :tangle sxhkdrc
super + v
  $TERMINAL -e $EDITOR
#+end_src

if =$EDITOR= somehow has an emacs script then this will run its GUI version
#+begin_src sh :tangle sxhkdrc
super + shift + v
  $EDITOR
#+end_src

*** browser

a graphical browser, set by =$BROWSER=
#+begin_src sh :tangle sxhkdrc
super + w
  $BROWSER
#+end_src

*** applicaction launcher

a run dialog & app launcher precisely
#+begin_src sh :tangle sxhkdrc
super + d
  dmenu_run -i -p 'summon:'
#+end_src

*** file manager

a graphical file manager, set by =$FILE=
#+begin_src sh :tangle sxhkdrc
super + e
  $FILE
#+end_src

*** rss feed

CLI rss feeder
#+begin_src sh :tangle sxhkdrc
super + n
  $TERMINAL -e newsboat
#+end_src

** controls

*** audio

CLI to control PulseAudio
#+begin_src sh :tangle sxhkdrc
super + a
  $TERMINAL -e pulsemixer
#+end_src

mute
#+begin_src sh :tangle sxhkdrc
XF86AudioMute
  pamixer -t && pkill -RTMIN+1 dwmblocks
#+end_src

increase/decrease
#+begin_src sh :tangle sxhkdrc
XF86Audio{Lower,Raise}Volume
  pamixer -{d,i} 5 && pkill -RTMIN+1 dwmblocks
#+end_src

*** brightness

increase/decrease
#+begin_src sh :tangle sxhkdrc
XF86MonBrightness{Down,Up}
  xbacklight -{dec,inc} 10 && pkill -RTMIN+2 dwmblocks
#+end_src

** tools

*** system monitor

CLI system activity monitor
#+begin_src sh :tangle sxhkdrc
super + shift + Escape
  $TERMINAL -e $SYS_MONITOR
#+end_src

*** password selector dropdown

#+begin_src sh :tangle sxhkdrc
super + p
  passmenu
#+end_src

*** display selector dropdown

#+begin_src sh :tangle sxhkdrc
super + F3
  displayselect
#+end_src

*** emoji / unicode list dropdown

#+begin_src sh :tangle sxhkdrc
super + grave
  dmenuunicode
#+end_src

*** screenshot utility dropdown

#+begin_src sh :tangle sxhkdrc
Print
  maimpick
#+end_src

*** system options dropdown

#+begin_src sh :tangle sxhkdrc
super + shift + x
  sysfns
#+end_src

*** network tools

CLI for /Network Manager/
#+begin_src sh :tangle sxhkdrc
super + F12
  $TERMINAL -e sudo nmtui
#+end_src

**** torrent tools

toggle the /transmission/ daemon with =F6= and launch the cli with =F7=
#+begin_src sh :tangle sxhkdrc
super + F{6,7}
 {td-toggle,torwrap}
#+end_src

*** mouting tools

#+begin_src sh :tangle sxhkdrc
super + F{9,10}
    {dmenumount,dmenuumount}
#+end_src

*** kill current window

kills currently focused window, an alternative to window manager's built-in
window close functionaly. this should be used as last resource
#+begin_src sh :tangle sxhkdrc
alt + F4
  kill -15 $(xdotool getactivewindow getwindowpid)
#+end_src

*** kill Xorg session

meant to kill the x server in an emergency situation
#+begin_src sh :tangle sxhkdrc
super + control + alt + Escape
  pkill -15 "Xorg"
#+end_src

* reload configuration

=sxhkd= reloads upon receiving signal =USR1=

#+begin_src sh
pkill -USR1 "sxhkd"
#+end_src
