#!/bin/sh

#  ██                        ██              ██  ██
# ░██                       ░██             ░██ ░██
# ░██       ██████    ██████░██  ██  █████  ░██ ░██
# ░██████  ░░░░░░██  ██░░░░ ░██ ██  ██░░░██ ░██ ░██
# ░██░░░██  ███████ ░░█████ ░████  ░███████ ░██ ░██
# ░██  ░██ ██░░░░██  ░░░░░██░██░██ ░██░░░░  ░██ ░██
# ░██  ░██░░████████ ██████ ░██░░██░░██████ ███ ███
# ░░   ░░  ░░░░░░░░ ░░░░░░  ░░  ░░  ░░░░░░ ░░░ ░░░

# install only if not already installed
if test ! -d "${HOME}/.ghcup"; then
    # install ghcup (GHC manager)
    curl --proto '=https' --tlsv1.2 -Sfs 'https://get-ghcup.haskell.org' | sh

else
    printf "ghcup is already installed @ %s/.ghcup\n" "${HOME}"
fi

# update Cabal (Haskell's package manager)
cabal update

# packages to be installed by cabal
pkgs='hindent hlint '

for pkg in ${pkgs}; do
    cabal install "${pkg}"

    unset -v pkg
done

# cleanup
unset -v pkgs
