#!/bin/sh

# tex-lang --- LaTeX setup.

# checks
! root-p && err 'This scripts needs root access.' && exit 1

if installed-p 'pacman'; then
    # compiler & tools
    pacman --needed --noconfirm -Syu 'texlive-most' 'biber' 'pandoc'
fi

# void stuff
#   # compiler & tools
#   $PKG_INSTALL "texlive-bin" "biber" "pandoc"

#   # == tlmgr
#   # gnupg is required to install via tlmgr
#   $PKG_INSTALL "gnupg"

#   # update
#   tlmgr update --all

#   tlmgr install biblatex
#   tlmgr install biblatex-apa
#   tlmgr install biblatex-ieee
#   tlmgr install capt-of
#   tlmgr install wrapfig

#   # cleanup
#   tlmgr update --all
#   texhash

# -----------------------------------------------------------------------------
# references
# -----------------------------------------------------------------------------

# https://0x0.st/XmyQ
