#!/bin/sh

# functionrc --- Functions for the shell

# -----------------------------------------------------------------------------
# miscellaneous
# -----------------------------------------------------------------------------

loop_ip() {
    # **
    # loop public IP address; optionally pass a delay as parameter
    # *

    while :; do
        printf '%s\n' "$(curl --limit-rate '1' -Ss 'ifconfig.me')"
        sleep "${1:-3}"
    done
}

sscreenkey() {
    # **
    # toggles screenkey, with some defaults
    # *

    if ! { pgrep 'screenkey' >/dev/null; }; then
        setsid -f screenkey --vis-shift --bak-mode full --mods-mode 'tux'\
               --opacity 0.6 --compr-cnt 2 -M --mouse-fade 2 \
               -f FantasqueSansMono -t 2 -p 'bottom' -s 'small' --show-settings
    else
        # kill if already running
        pkill -15 'screenkey'
    fi
}

magit() {
    # **
    # magit on the terminal (via emacs)
    # *

    magit_cmd="(magit-status \"`git rev-parse --show-toplevel`\")"

    { ! pgrep 'emacs' && emacs -nw --eval "${magit_cmd}"; } \
        || emacsclient -nw --eval "${magit_cmd}";
}

bitrate() {
    # **
    # retrieves the bitrate of an audio file
    # *

    ffprobe "$1" 2>&1 | grep 'rate'
}

gpg_export_pub_key() {
    # **
    # export public GPG key
    # *

    gpg --output "${HOME}/temp/pub_key.pgp" --armor --export "$1"
}

gpg_export_sec_key() {
    # **
    # export secret GPG key
    # *

    gpg --output "${HOME}/temp/sec_key.pgp" --armor --export-secret-key "$1"
}

gpg_import_key() {
    # **
    # import GPG key :: public/private
    # *

    gpg --import "$1"
    printf "\nkeys: %s\n\nuse 'gpg --edit-keys <mail>' to set trust level\n" \
           "$(gpg --list-keys)"
}
