[".local/bin/pfetch"]
    type          = "file"
    executable    = true
    url           = "https://raw.githubusercontent.com/dylanaraps/pfetch/master/pfetch"
    refreshPeriod = "168h"

[".config/bash/plugins/git-prompt.sh"]
    type          = "file"
    executable    = true
    url           = "https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh"
    refreshPeriod = "168h"
