# -----------------------------------------------------------------------------
# scripts
# -----------------------------------------------------------------------------

[".local/bin/pfetch"]
    type          = "file"
    executable    = true
    url           = "https://raw.githubusercontent.com/dylanaraps/pfetch/master/pfetch"
    refreshPeriod = "168h"

# -----------------------------------------------------------------------------
# shell
# -----------------------------------------------------------------------------

[".config/shell/plugins/git-prompt.sh"]
    type          = "file"
    executable    = true
    url           = "https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh"
    refreshPeriod = "168h"

# -----------------------------------------------------------------------------
# zsh
# -----------------------------------------------------------------------------

[".config/zsh/plugins/fast-syntax-highlighting/"]
    type = "archive"
    stripComponents = 1
    url = "https://github.com/zdharma-continuum/fast-syntax-highlighting/archive/master.tar.gz"
    refreshPeriod = "168h"

[".config/zsh/plugins/zsh-autosuggestions/"]
    type = "archive"
    stripComponents = 1
    url = "https://github.com/zsh-users/zsh-autosuggestions/archive/master.tar.gz"
    refreshPeriod = "168h"

# -----------------------------------------------------------------------------
# resources
# -----------------------------------------------------------------------------

[".local/resources/emoji.txt"]
    type          = "file"
    url           = "https://gitlab.com/-/snippets/2330828/raw/main/emoji.txt"
    refreshPeriod = "168h"

[".local/resources/boxes-demo.txt"]
    type          = "file"
    url           = "https://raw.githubusercontent.com/GNOME/vte/master/doc/boxes.txt"
    refreshPeriod = "168h"

[".local/resources/utf8-demo.txt"]
    type          = "file"
    url           = "https://www.cl.cam.ac.uk/~mgk25/ucs/examples/UTF-8-demo.txt"
    refreshPeriod = "168h"
