---

- name: Install personal GNU Emacs configuration
  git:
    repo: "https://git.sr.ht/~anntnzrb/.emacs.d"
    dest: "{{ cfg_dir }}/emacs.vanilla/"

- name: Install personal Doom GNU Emacs configuration
  git:
    repo: "https://git.sr.ht/~anntnzrb/.doom.d"
    dest: "{{ cfg_dir }}/doom.bak/"
