git:
    github:
        token: ENC[AES256_GCM,data:nyiJ2LCEWOmd9kL05g/L2ZQAqMLNb6Gvzh+vIJgnHnvaOuWrCon9mw==,iv:zGtCMdgWysf7K0K9qZuOnU7zLJ6tVPTISciYi6tX+1o=,tag:k3icgQLlUEvQMkSGLD70xA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l6alqg2fuht0hvxrk5ehndrhjgux7p9yrf7mpl9dk9s3xcq2y39shcflw0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyWXo1YUZiZld3a1pEOU1I
            SDBubUI0bTYxVmF4eDZZTlRhcmgxRFo0QVRJCkJnUDNqeUR5RHYyV2hkKzdYcWFE
            dzdWNVBLZi84RnFpb21COFpvWkQzWmsKLS0tIEc1MXpxRVpTd0Fvc0ZCMVQrTmZD
            VmllRjdkdk1qYm84VWVYdkg1OUoyaEUKj6P2x3gg6bJBBiWZYuB5o23Mb/9keSMq
            isR+v0ohDek48vq0f9NbMAHohEhZ9Zc9/GzdMHG5KafW1Os5tD1tEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-07T05:32:59Z"
    mac: ENC[AES256_GCM,data:4zyZI3JKokFWhKohjeMRO6C6XikaG8ZLovzPWF3oXi8yne8Rw1k3GzmnqW4szsYWeG/XYrJdif9lPFZ/pjECBWsFYex6OzqpnRaSQikneYzrBC9dFK2jYa1e7MJs1o0nKCndIXro45e0/g0tGSK4lvhBES69dauKAkYB8nK2lVY=,iv:1t0XTfVDP//G45YL1YmtYtXUcVIVc9yrYR2wVRtFeZw=,tag:ut37crxOQu/Zqis8LTaKJQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
