#!/bin/sh

#             ██ ██
#            ░██░░
#   ██████   ░██ ██  ██████    ██████  █████   ██████
#  ░░░░░░██  ░██░██ ░░░░░░██  ██░░░░  ██░░░██ ██░░░░
#   ███████  ░██░██  ███████ ░░█████ ░███████░░█████
#  ██░░░░██  ░██░██ ██░░░░██  ░░░░░██░██░░░░  ░░░░░██
# ░░████████ ███░██░░████████ ██████ ░░██████ ██████
#  ░░░░░░░░ ░░░ ░░  ░░░░░░░░ ░░░░░░   ░░░░░░ ░░░░░░

#◦◝◟∘◞◜◦ colors / settings / verbosity
alias \
    cp="cp -irv" \
    diff="diff --color=auto" \
    grep="grep -i --color=auto" \
    ls="ls -AFh --color=auto --group-directories-first" \
    ll="ls -AFho --color=auto --group-directories-first" \
    mkdir="mkdir -pv" \
    mv="mv -iv" \
    rm="rm -v" \
    rmfr="rm -frv" \
    zip="zip -rv"

#◦◝◟∘◞◜◦ shortcuts
alias \
    e='$EDITOR' \
    se='sudo $EDITOR' \
    sx11="startx" \
    kx11="sudo pkill -x Xorg"

#◦◝◟∘◞◜◦ distro-specific aliases
# arch-based
[ -x "$(command -v pacman)" ] &&
    alias \
        pkgf="pacman -Ss" \
        pkgi="sudo pacman -S" \
        pkgr="sudo pacman -R" \
        pkgu="sudo pacman -Suyy"

# void
[ -x "$(command -v xbps-install)" ] &&
    alias \
        pkgf="xbps-query" \
        pkgi="sudo xbps-install -fu xbps && sudo xbps-install -Sf" \
        pkgr="sudo xbps-remove -f" \
        pkgu="sudo xbps-install -fu xbps && sudo xbps-install -Sfu"

#◦◝◟∘◞◜◦ misc
alias \
    ascii="toilet -t -f 3d" \
    future="toilet -t -f future" \
    matrix="unimatrix -a -l GRgors -s 96" \
    rusto="toilet -t -f rusto" \
    rustofat="toilet -t -f rustofat" \
    tnet="ping 1.1.1.1" \
    tnetspeed="speedtest-cli" \
    yta="youtube-dl --extract-audio --audio-format best" \
    ytv="youtube-dl -f best"

sscreenkey() {
    command pkill -9 screenkey >/dev/null 2>&1
    setsid screenkey --no-systray --vis-shift --bak-mode full \
        --opacity 0.55 -f FiraCodeRetina -t 2 \
        -p bottom -s small >/dev/null 2>&1 &
}
