#!/usr/bin/env sh

#    ████                            ██   ██
#   ░██░                            ░██  ░░
#  ██████ ██   ██ ███████   █████  ██████ ██  ██████  ███████   ██████
# ░░░██░ ░██  ░██░░██░░░██ ██░░░██░░░██░ ░██ ██░░░░██░░██░░░██ ██░░░░
#   ░██  ░██  ░██ ░██  ░██░██  ░░   ░██  ░██░██   ░██ ░██  ░██░░█████
#   ░██  ░██  ░██ ░██  ░██░██   ██  ░██  ░██░██   ░██ ░██  ░██ ░░░░░██
#   ░██  ░░██████ ███  ░██░░█████   ░░██ ░██░░██████  ███  ░██ ██████
#   ░░    ░░░░░░ ░░░   ░░  ░░░░░     ░░  ░░  ░░░░░░  ░░░   ░░ ░░░░░░

# git
qgc() {
    git clone -q "$1" ~/temp/"$2" || exit
    cd ~/temp/"$2" || exit
    notify-send -t 0 "repository cloned to ~/temp/$2"
}

# misc
url_short() {
    curl -Ss -F"shorten=$*" https://0x0.st | xclip -selection clipboard || exit
    notify-send -t 0 "link copied to clipboard"
}

file_upl() {
    curl -Ss -F"file=@$*" https://0x0.st | xclip -selection clipboard || exit
    notify-send -t 0 "link copied to clipboard"
}

dddd() {
    sudo dd if="$1" of="$2" bs=1M status=progress && sync || exit
    notify-send -t 0 "dd finished its job"
}

sh_script() {
    SCRIPT_PATH="$HOME/.local/bin/$1"

    if [ -f "$SCRIPT_PATH" ]; then
        echo "file already exists"
    else
        printf '#!/bin/sh\n\n' >"$SCRIPT_PATH"
        chmod +x "$SCRIPT_PATH"
        $EDITOR "$SCRIPT_PATH"
    fi
}

#◦◝◟∘◞◜◦ distro-specific
# arch

[ -x "$(command -v pacman)" ] &&
    add_key() {
        sudo pacman-key --recv-keys "$1" &&
            sudo pacman-key --finger "$1" &&
            sudo pacman-key --lsign-key "$1" &&
            sudo pacman --noconfirm -Syy archlinux-keyring
    }
