#!/usr/bin/env sh

#    ████                            ██   ██
#   ░██░                            ░██  ░░
#  ██████ ██   ██ ███████   █████  ██████ ██  ██████  ███████   ██████
# ░░░██░ ░██  ░██░░██░░░██ ██░░░██░░░██░ ░██ ██░░░░██░░██░░░██ ██░░░░
#   ░██  ░██  ░██ ░██  ░██░██  ░░   ░██  ░██░██   ░██ ░██  ░██░░█████
#   ░██  ░██  ░██ ░██  ░██░██   ██  ░██  ░██░██   ░██ ░██  ░██ ░░░░░██
#   ░██  ░░██████ ███  ░██░░█████   ░░██ ░██░░██████  ███  ░██ ██████
#   ░░    ░░░░░░ ░░░   ░░  ░░░░░     ░░  ░░  ░░░░░░  ░░░   ░░ ░░░░░░

# git
qgc() {
    git clone -q "$1" ~/temp/"$2" || exit
    cd ~/temp/"$2" || exit
    fnNotify 0 "repository cloned to ~/temp/$2"
}

# misc
url_short() {
    curl -Ss -F"shorten=$*" https://0x0.st | xclip -selection clipboard || exit
    fnNotify 0 "link copied to clipboard"
}

file_upl() {
    curl -Ss -F"file=@$*" https://0x0.st | xclip -selection clipboard || exit
    fnNotify 0 "link copied to clipboard"
}

dddd() {
    sudo dd if="$1" of="$2" bs=1M status=progress && sync || exit
    fnNotify 0 "dd finished copying $2"
}

sh_script() {
    SCRIPT_PATH="$HOME/.local/bin/$1"

    if [ -f "$SCRIPT_PATH" ]; then
        echo "file already exists"
    else
        printf '#!/bin/sh\n\n' >"$SCRIPT_PATH"
        chmod +x "$SCRIPT_PATH"
        $EDITOR "$SCRIPT_PATH"
    fi
}

#◦◝◟∘◞◜◦ distro-specific
# arch

[ -x "$(command -v pacman)" ] &&
    add_key() {
        sudo pacman-key --recv-keys "$1" &&
            sudo pacman-key --finger "$1" &&
            sudo pacman-key --lsign-key "$1" &&
            sudo pacman --noconfirm -Syy archlinux-keyring
    }

#◦◝◟∘◞◜◦ misc

# checks if dunst is installed; receives parameters
fnNotify() {
    [ -x "$(command -v notify-send)" ] &&
        pgrep -x Xorg >/dev/null 2>&1 &&
        notify-send -t "$1" "$2"
}

# loop public ip address
loop_ip() {
    ping -q -c 1 1.1.1.1 >/dev/null 2>&1 && {
        while :; do
            curl ifconfig.me
            echo
            sleep "${1:-3}"
        done
    } || printf 'N/A\n'
}

# loop vpn
loop_vpn() {
    [ -x "$(command -v vyprvpn)" ] && ping -q -c 1 1.1.1.1 >/dev/null 2>&1 && {
        while :; do
            vyprvpn disconnect
            sleep 3
            vyprvpn connect
            sleep "${1:-600}"
        done
    } || printf 'N/A\n'
}
