#!/bin/sh

#             ██ ██
#            ░██░░
#   ██████   ░██ ██  ██████    ██████  █████   ██████
#  ░░░░░░██  ░██░██ ░░░░░░██  ██░░░░  ██░░░██ ██░░░░
#   ███████  ░██░██  ███████ ░░█████ ░███████░░█████
#  ██░░░░██  ░██░██ ██░░░░██  ░░░░░██░██░░░░  ░░░░░██
# ░░████████ ███░██░░████████ ██████ ░░██████ ██████
#  ░░░░░░░░ ░░░ ░░  ░░░░░░░░ ░░░░░░   ░░░░░░ ░░░░░░

# -----------------------------------------------------------------------------
# general
# -----------------------------------------------------------------------------

alias \
    cp='cp -Riv' \
    diff='diff --color=auto' \
    grep='grep -i --color=auto' \
    ls='ls -AFhq --color=auto --group-directories-first' \
    ll='ls -AFhlq --color=auto --group-directories-first' \
    mkdir='mkdir -pv' \
    lsblk='lsblk -ap' \
    mv='mv -iv' \
    rm='rm -v' \
    rmfr='rm -Rfv' \
    tree='tree -CFlq --dirsfirst' \
    treed='tree -CFdlq --dirsfirst' \
    zip='zip -rv'

# shortcuts
alias \
    eed='${EDITOR:?}' \
    seed='sudo ${EDITOR:?}' \
    sx11='startx ${HOME}/.xinitrc' \
    kx11="pkill -15 'X'"

# -----------------------------------------------------------------------------
# miscellaneous
# -----------------------------------------------------------------------------

alias \
    ascii="toilet -t -f '3d'" \
    cheat='cht.sh' \
    future="toilet -t -f 'future'" \
    rusto="toilet -t -f 'rusto'" \
    rustofat="toilet -t -f 'rustofat'" \
    tnet="ping 'example.com'" \
    tnetspeed='speedtest-cli' \
    yt='youtube-dl --restrict-filenames' \
    ytf='youtube-dl -F' \
    ytt='youtube-dl --restrict-filenames --skip-download --write-thumbnail' \
    yta="youtube-dl --restrict-filenames --prefer-ffmpeg --audio-format 'best' -x" \
    ytv="youtube-dl --restrict-filenames -f 'best'"
