#!/bin/sh

#    ████                            ██   ██
#   ░██░                            ░██  ░░
#  ██████ ██   ██ ███████   █████  ██████ ██  ██████  ███████   ██████
# ░░░██░ ░██  ░██░░██░░░██ ██░░░██░░░██░ ░██ ██░░░░██░░██░░░██ ██░░░░
#   ░██  ░██  ░██ ░██  ░██░██  ░░   ░██  ░██░██   ░██ ░██  ░██░░█████
#   ░██  ░██  ░██ ░██  ░██░██   ██  ░██  ░██░██   ░██ ░██  ░██ ░░░░░██
#   ░██  ░░██████ ███  ░██░░█████   ░░██ ░██░░██████  ███  ░██ ██████
#   ░░    ░░░░░░ ░░░   ░░  ░░░░░     ░░  ░░  ░░░░░░  ░░░   ░░ ░░░░░░

# -----------------------------------------------------------------------------
# miscellaneous
# -----------------------------------------------------------------------------

shorten_url() {
    # **
    # shorten URLs with 0x0.st
    # *

    { curl -Ss -F "shorten=$*" 'https://0x0.st' | xclip -sel clip; } || return 1
    printf 'link(s) copied to clipboard\n'
}

upl_file() {
    # **
    # upload files to 0x0.st (expire)
    # *

    { curl -Ss -F "file=@$*" 'https://0x0.st' | xclip -sel clip; } || return 1
    printf 'link(s) copied to clipboard\n'
}

dddd() {
    # **
    # alias for dd with a few flags
    # *

    { sudo -E dd bs=1M status=progress if="$1" of="$2" && sync; } || return 1
    printf "dd finished copying '%s'\n" "$2"
}

loop_ip() {
    # **
    # loop thru public IP address
    # *

    while :; do
        printf '%s\n' "$(curl --limit-rate '1' -Ss 'ifconfig.me')"
        sleep "${1:-3}"
    done
}

# loop VPN
loop_vpn() {
    # **
    # constantly disconnect and connect VPN to refresh sessions
    # should be used along with a kill-switch
    # *

    # sudo timeout is 300s by default
    while :; do
        sudo -v || return 1
        protonvpn s | grep -q 'Disconnected' && sudo -E protonvpn r
        sleep "${1:-290}"
    done
}

# -----------------------------------------------------------------------------
# miscellaneous
# -----------------------------------------------------------------------------

sscreenkey() {
    # **
    # toggles screenkey, with some defaults
    # *

    if ! { pgrep -x 'screenkey' >/dev/null; }; then
        setsid -f screenkey --no-systray --vis-shift --bak-mode full \
            --opacity 0.55 -f FiraCodeRetina -t 2 -p bottom -s small \
            --show-settings
    else
        # kill if already running
        pkill -15 'screenkey'
    fi
}

bitrate() {
    # **
    # retrieves the bitrate of a file (audio)
    # *

    ffprobe "$1" 2>&1 | grep 'rate'
}

gpg_export_pub_key() {
    # **
    # export public GPG key
    # *

    gpg --output "${HOME}/temp/pub_key.pgp" --armor --export "$1"
}

gpg_export_sec_key() {
    # **
    # export secret GPG key
    # *

    gpg --output "${HOME}/temp/sec_key.pgp" --armor --export-secret-key "$1"
}

gpg_import_key() {
    # **
    # import GPG key :: public/private
    # *

    gpg --import "$1"
    printf "\nkeys: %s\n\nuse 'gpg --edit-keys <mail>' to set trust level\n" \
        "$(gpg --list-keys)"
}

# -----------------------------------------------------------------------------
# distro-especific
# -----------------------------------------------------------------------------

test -x "$(command -v 'pacman')" && {
    add_key() {
        # **
        # adds a pacman key
        # TODO: fix multiple use of sudo
        # *

        sudo pacman-key --recv-keys "$1" &&
            sudo pacman-key --finger "$1" &&
            sudo pacman-key --lsign-key "$1" &&
            sudo pacman --noconfirm -Syy archlinux-keyring
    }
}
