#!/bin/sh

git clone -q https://github.com/xero/figlet-fonts.git ~/temp/figlet-fonts || exit
sudo mv -fv ~/temp/figlet-fonts/* /usr/share/figlet/ >/dev/null || exit
rm -fr ~/temp/figlet-fonts/ >/dev/null

printf '\nfiglet fonts were downloaded and applied...\n'
