#!/bin/sh

# -----------------------------------------------------------------------------
# functions
# -----------------------------------------------------------------------------

# **
# checks if script was ran as SU, elevates if not
# *

elevate_perms() { [ "$(id -u)" -ne 0 ] && exec sudo "$0" "$@"; }

# -----------------------------------------------------------------------------
# main
# -----------------------------------------------------------------------------

# elevate permissions
elevate_perms "$@"

# set download folder
DWNL_FOLDER="/tmp/figlet-fonts"

# download & install
git clone -q "https://github.com/xero/figlet-fonts.git" "$DWNL_FOLDER" ||
    exit 1
cp -Tfr "$DWNL_FOLDER/." "/usr/share/figlet/" || exit 1
rm -fr "$DWNL_FOLDER"

printf 'figlet fonts were downloaded and applied...\n'
