#+TITLE: GNU Emacs configurations
#+AUTHOR: anntnzrb
#+EMAIL: anntnzrb@protonmail.com
#+PROPERTY: header-args :results silent
#+MACRO: export-date (eval (format-time-string "%F" (current-time)))

+ created: 2020-11-07
+ updated: *{{{export-date}}}*

* Table of Contents                                       :TOC_2_gh:noexport:
- [[#early-init-file][Early Init File]]
- [[#init-file][Init File]]
- [[#settings][Settings]]
  - [[#custom][Custom]]
  - [[#package-management][Package Management]]
  - [[#editing][Editing]]
  - [[#modeline][Modeline]]
  - [[#appearance][Appearance]]
  - [[#dired][Dired]]
  - [[#utilities][Utilities]]
  - [[#miscellaneous][Miscellaneous]]
- [[#org-mode][Org-Mode]]
- [[#programming][Programming]]
  - [[#version-control][Version Control]]
  - [[#language-server-protocol-lsp][Language Server Protocol (LSP)]]
  - [[#linting][Linting]]
  - [[#completion][Completion]]
  - [[#snippets][Snippets]]
  - [[#generic-formatter][Generic Formatter]]
  - [[#shell][Shell]]
  - [[#c][C]]
  - [[#rust][Rust]]
  - [[#emacs-lisp-elisp][Emacs Lisp (elisp)]]
  - [[#python][Python]]

* Early Init File

Emacs =27.1= offers new file called =early-init.el= which allows customizations
that take effect during Emacs startup earlier than the normal init file. This
file is loaded before the package system and GUI is initialized.

*References*: [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Early-Init-File.html][The Early Init File]]

#+begin_src emacs-lisp :tangle "early-init.el"
;;; early-init.el --- GNU Emacs >= 27.1 pre-initialization file

;;; Commentary:

;; This file gets loaded before the 'init.el' file.
;; Should not have more than a few files.

;;; Code:

;; Package tweaks
(setq-default package-enable-at-startup t
              package-quickstart        t)

(provide 'early-init)

;;; early-init.el ends here
#+end_src

* Init File

#+begin_src emacs-lisp :tangle "init.el"
;;; init.el --- Initialization file of GNU Emacs

;;; Commentary:
;; This file gets loaded after the 'early-init.el' file.

;;; Code:

(org-babel-load-file (expand-file-name "readme.org" user-emacs-directory))

(provide 'init)
;;; init.el ends here
#+end_src

* Settings

#+begin_src emacs-lisp
(setq-default inhibit-startup-screen  t
              initial-scratch-message nil
              initial-buffer-choice   (expand-file-name "~"))

;; Others
(setq-default global-auto-revert-mode t)

;; Custom(ize) file
(setq-default custom-file (expand-file-name "custom.el" user-emacs-directory))

;; Shorter prompts
(fset 'yes-or-no-p 'y-or-n-p)
#+end_src

** Custom

Section where I place my own functions/definitions that do not belog anywhere
specific.

#+begin_src emacs-lisp
(defun annt/add-multi-hook (fun hooks)
  "Adds FUN to multiple HOOKS."
  (mapc (lambda (hook)
          (add-hook hook fun))
        hooks))
#+end_src

** Package Management

#+begin_src emacs-lisp
(require 'package)

(add-to-list 'package-archives
             '("MELPA Stable" . "https://stable.melpa.org/packages/") t)

(package-initialize)

; only refresh if needed
(unless package-archive-contents (package-refresh-contents))

(defun annt/install-pkg(pkg)
  "Checks if 'PKG' is installed and if not, installs it."
  (unless (package-installed-p pkg)
    (unless package-archive-contents (package-refresh-contents))
    (package-install pkg)))
#+end_src

** Editing

#+begin_src emacs-lisp
(setq-default mode-require-final-newline t
              show-trailing-whitespace   t
              indent-tabs-mode           nil
              tab-width   4
              fill-column 79
              display-fill-column-indicator-column (+ fill-column 1))

;; delete trailing whitespaces prior save
(add-hook 'before-save-hook #'delete-trailing-whitespace)

;; display vertical column at line limit
(annt/add-multi-hook #'display-fill-column-indicator-mode
                     '(prog-mode-hook
                       text-mode-hook))

;; auto-wrapping
(annt/add-multi-hook #'auto-fill-mode
                     '(prog-mode-hook
                       text-mode-hook))
#+end_src

** Modeline

#+begin_src emacs-lisp
(setq-default column-number-mode   t
              size-indication-mode t
              column-number-indicator-zero-based nil)
#+end_src

** Appearance

#+begin_src emacs-lisp
(menu-bar-mode   0)
(tool-bar-mode   0)
(scroll-bar-mode 0)

(defconst annt/FONT_NAME "VictorMono")
(defconst annt/FONT_SIZE           13)
(defconst annt/FULL_FONT (format "%s-%s" annt/FONT_NAME annt/FONT_SIZE))

(set-face-attribute 'default nil :font annt/FULL_FONT)
(set-frame-font     annt/FULL_FONT nil t)

;; Theme
;; only enable if running Emacs as an X window
(when (display-graphic-p) (load-theme 'misterioso t))
#+end_src

** Dired

#+begin_src emacs-lisp
(setq-default dired-listing-switches  "-Fahlq --group-directories-first"
              dired-recursive-copies  'always
              dired-recursive-deletes 'always
              dired-use-ls-dired      'unspecified)
#+end_src

** Utilities

*** Which-Key

#+begin_src emacs-lisp
(annt/install-pkg 'which-key) ;; PKG installation

;; Settings
(setq-default which-key-is-verbose t
              which-key-idle-delay 0.5
              which-key-lighter "")

(which-key-mode) ;; Enable mode
#+end_src

*** Helpful

#+begin_src emacs-lisp
(annt/install-pkg 'helpful) ;; PKG installation

;; Keybinds
(global-set-key [remap describe-command]  #'helpful-command)
(global-set-key [remap describe-function] #'helpful-function)
(global-set-key [remap describe-key]      #'helpful-key)
(global-set-key [remap describe-symbol]   #'helpful-symbol)
(global-set-key [remap describe-variable] #'helpful-variable)
#+end_src

*** Vi Emulation

**** Evil

#+begin_src emacs-lisp
(annt/install-pkg 'evil) ;; PKG installation

;; Settings
(setq-default evil-want-minibuffer t
              evil-want-keybinding nil)

(evil-mode) ;; Init
#+end_src

**** Evil Surround

#+begin_src emacs-lisp
(annt/install-pkg 'evil-surround) ;; PKG installation

;; Hooks
(annt/add-multi-hook #'evil-surround-mode
                     '(prog-mode-hook
                       text-mode-hook))

(global-evil-surround-mode) ;; Init
#+end_src

*** Aggressive-indent

#+begin_src emacs-lisp
(annt/install-pkg 'aggressive-indent) ;; PKG installation

;; Settings
(setq-default aggressive-indent-comments-too t
              aggressive-indent-sit-for-time 0.5)
;; Hooks
(add-hook 'prog-mode-hook #'aggressive-indent-mode)
#+end_src

** Miscellaneous

+ Enable Emacs server on initialization

#+begin_src emacs-lisp
(add-hook 'after-init-hook #'server-start)
#+end_src

+ Don't prompt when killing buffer

#+begin_src emacs-lisp
(global-set-key [remap kill-buffer] #'kill-this-buffer)
#+end_src

*** Backups

#+begin_src emacs-lisp
(setq-default create-lockfiles  nil
              make-backup-files nil)
#+end_src
* Org-Mode

#+begin_src emacs-lisp
(annt/install-pkg 'org) ;; PKG installation

;; Backends for Org Exportation
(setq-default org-export-backends '(html latex man md odt))


;; General Org settings
(setq-default org-export-with-email t
              org-edit-src-content-indentation 0
              org-confirm-babel-evaluate       nil)

;; Languages to work with Babel
(setq-default org-babel-load-languages
              '((emacs-lisp . t)
                (shell      . t)
                (C          . t)
                (python     . t)))

;; Templates
(require 'org-tempo) ;; needed for templates to work

(setq-default org-structure-template-alist
              '(("src" . "src")
                ;; languages
                ("el"  . "src emacs-lisp")
                ("sh"  . "src sh")
                ("c"   . "src c")
                ("py"  . "src python")
                ;; misc
                ("comm" . "comment")
                ("ex"   . "example")
                ("quo"  . "quote")))

;; Hooks
(add-hook 'org-mode-hook #'org-indent-mode)
#+end_src

*** Table of Contents for Org

#+begin_src emacs-lisp
(annt/install-pkg 'toc-org) ;; PKG installation

(add-hook 'org-mode-hook #'toc-org-mode)
#+end_src

* Programming

** Version Control

#+begin_src emacs-lisp
;; Follow some good git practices
(defconst annt/GIT_MSG_MAX_SIZE 50)

(setq-default git-commit-summary-max-length annt/GIT_MSG_MAX_SIZE
              git-commit-style-convention-checks
              '(non-empty-second-line overlong-summary-line))
#+end_src

*** Magit

Interactive Git

#+begin_src emacs-lisp
(annt/install-pkg 'magit) ;; PKG install

;; Keybinds
(global-set-key (kbd "C-c g") 'magit-status)
#+end_src

** Language Server Protocol (LSP)

#+begin_src emacs-lisp
(annt/install-pkg 'lsp-mode)

;; Settings
(setq lsp-keymap-prefix "C-c l")
#+end_src

** Linting

#+begin_src emacs-lisp
(annt/install-pkg 'flycheck) ;; PKG install

;; Settings
(setq-default flycheck-mode-line-prefix "FlyCheck"
              flycheck-checker-error-threshold 100
              flycheck-display-errors-delay 1
              flycheck-idle-change-delay    1)
#+end_src

** Completion

#+begin_src emacs-lisp
(annt/install-pkg 'company) ;; PKG installation

;; Settings
(setq-default company-minimum-prefix-length 2
              company-idle-delay 0.25
              company-show-numbers ''t)
#+end_src

** Snippets

#+begin_src emacs-lisp
;; Settings
(annt/install-pkg 'yasnippet)          ;; PKG Installation
(annt/install-pkg 'yasnippet-snippets) ;; PKG Installation
(add-hook 'prog-mode-hook #'yas-minor-mode)
#+end_src

#+end_src
** Generic Formatter

#+begin_src emacs-lisp
(annt/install-pkg 'reformatter) ;; PKG installation
#+end_src

** Shell

#+begin_src emacs-lisp
(setq-default sh-backslash-column fill-column
              sh-indent-after-case 0)

;; Linting
(add-hook 'sh-mode-hook #'flycheck-mode)

;; Completion
(add-hook 'sh-mode-hook #'company-mode)
#+end_src

** C

#+begin_src emacs-lisp
;; GNU-styled with a few tweaks
(setq-default c-set-style "gnu"
              c-basic-offset 4)

;; Formatter
(defcustom c-fmt-command "uncrustify"
  "Command used to format C files."
  :group 'c
  :type  'file
  :safe  'stringp)

(reformatter-define c-fmt-command
  :group   'c
  :program "uncrustify"
  :args    '("--no-backup"))

;; keybind assignment for the formatter
(add-hook 'c-mode-hook (lambda ()
                         (local-set-key (kbd "C-c c f") 'c-fmt-command)))
#+end_src

** Rust

Rust programming is not part of Emacs, there's not even a hook for it.
[[https://github.com/rust-lang/rust-mode][Rust Mode]] accounts for this.

#+begin_src emacs-lisp
(annt/install-pkg 'rust-mode) ;; PKG install

;; Settings
(setq-default rust-always-locate-project-on-open t
              rust-format-on-save t)
#+end_src

[[Language Server Protocol (LSP) ]]for Rust. Flycheck and Company were not enough
for this for some reason, I might re-try them in the future. LSP works well for
now.

#+begin_src emacs-lisp
(add-hook 'rust-mode-hook #'lsp-deferred)
#+end_src

*** Package Manager for Rust

#+begin_src emacs-lisp
(annt/install-pkg 'cargo) ;; PKG install

;; Hooks
(add-hook 'rust-mode-hook 'cargo-minor-mode)
#+end_src

** Emacs Lisp (elisp)

#+begin_src emacs-lisp
;; Checkdoc
(setq-default checkdoc-verb-check-experimental-flag nil)

;; Linting
(add-hook 'emacs-lisp-mode-hook #'flycheck-mode)

;; Completion
(add-hook 'emacs-lisp-mode-hook #'company-mode)
#+end_src
** Python

#+begin_src emacs-lisp
;; Linting
(add-hook 'python-mode-hook #'flycheck-mode)

;; Completion
(add-hook 'python-mode-hook #'company-mode)
#+end_src
