#!/bin/sh

#             ██ ██
#            ░██░░
#   ██████   ░██ ██  ██████    ██████  █████   ██████
#  ░░░░░░██  ░██░██ ░░░░░░██  ██░░░░  ██░░░██ ██░░░░
#   ███████  ░██░██  ███████ ░░█████ ░███████░░█████
#  ██░░░░██  ░██░██ ██░░░░██  ░░░░░██░██░░░░  ░░░░░██
# ░░████████ ███░██░░████████ ██████ ░░██████ ██████
#  ░░░░░░░░ ░░░ ░░  ░░░░░░░░ ░░░░░░   ░░░░░░ ░░░░░░

# -----------------------------------------------------------------------------
# general
# -----------------------------------------------------------------------------

alias \
    cp="cp -aiv" \
    diff="diff --color=auto" \
    grep="grep -i --color=auto" \
    ls="ls -AFhq --color=auto --group-directories-first" \
    ll="ls -AFhlq --color=auto --group-directories-first" \
    mkdir="mkdir -pv" \
    mv="mv -iv" \
    rm="rm -v" \
    rmfr="rm -Rfv" \
    tree="tree -CFlq --dirsfirst" \
    treed="tree -CFdlq --dirsfirst" \
    zip="zip -rv"

# shortcuts
alias \
    eed='$EDITOR' \
    seed='sudo $EDITOR' \
    sx11="startx" \
    kx11="pkill -15 'Xorg'"

# -----------------------------------------------------------------------------
# system-specific aliases
# -----------------------------------------------------------------------------

# arch-based
if [ -x "$(command -v 'pacman')" ]; then
    alias \
        pkgf="pacman -Ss" \
        pkgi="sudo pacman -S" \
        pkgr="sudo pacman -R" \
        pkgu="sudo pacman -Suyy"

# void
elif [ -x "$(command -v 'xbps-install')" ]; then
    alias \
        pkgf="xbps-query" \
        pkgi="sudo xbps-install -S xbps && sudo xbps-install -S" \
        pkgr="sudo xbps-remove -Rf" \
        pkgu="sudo xbps-install -S xbps && sudo xbps-install -Su"
fi

# -----------------------------------------------------------------------------
# miscellaneous
# -----------------------------------------------------------------------------

alias \
    ascii="toilet -t -f '3d'" \
    cheat="cht.sh" \
    future="toilet -t -f 'future'" \
    matrix="unimatrix -a -l GRgors -s 96" \
    rusto="toilet -t -f 'rusto'" \
    rustofat="toilet -t -f 'rustofat'" \
    tnet="ping example.com" \
    tnetspeed="speedtest-cli" \
    yt="youtube-dl --restrict-filenames" \
    ytf="youtube-dl -F" \
    ytt="youtube-dl --restrict-filenames --skip-download --write-thumbnail" \
    yta="youtube-dl --restrict-filenames --prefer-ffmpeg --audio-format 'best' -x" \
    ytv="youtube-dl --restrict-filenames -f 'best'"
