#!/bin/sh

# aliasrc --- Aliases for the shell

# Commentary:

# These aliases are shell-agnostic with portability in mind.

# References:
# - https://wiki.archlinux.org/title/Core_utilities

# shellcheck disable=2006
# keep backticks for portability.

# -----------------------------------------------------------------------------
# core utilities
# -----------------------------------------------------------------------------
# use "modern UNIX utilities" (Rust implementation) if available, fallback to
# original commands otherwise.

# ls === exa
if test -x "`command -v 'exa'`"; then
    alias \
        ls='exa --color=automatic --group-directories-first --icons --sort=Name -Fagh' \
        ll='exa --color=automatic --group-directories-first --icons --sort=Name -Faglh'
else
    alias \
        ls='ls --color=auto --group-directories-first -AFhq'  \
        ll='ls --color=auto --group-directories-first -AFhlq'
fi

# cat/less === bat
if test -x "`command -v 'bat'`"; then
    alias \
        cat='bat --color=auto --theme="Monokai Extended Origin" --style=full -P' \
        less='bat --color=auto --theme="Monokai Extended Origin" --style=full'
else
    alias cat='cat -n'
fi

# rg (ripgrep) === grep
if test -x "`command -v 'rg'`"; then
    alias grep='rg --color=auto --column --hidden -Hin'
else
    alias grep='grep --color=auto -in'
fi

alias \
    ..='cd ..'                                                                \
    cd..='cd ..'                                                              \
    cp='cp -Riv'                                                              \
    diff='diff --color=auto'                                                  \
    mkdir='mkdir -pv'                                                         \
    lsblk='lsblk -ap'                                                         \
    mv='mv -iv'                                                               \
    rm='rm -v'                                                                \
    rmfr='rm -Rfv'                                                            \
    rmfrs='rm -Rf >/dev/null'                                                 \
    tree='exa --color=automatic --group-directories-first --icons -FTgh'      \
    treea='exa --color=automatic --group-directories-first --icons -FTagh'    \
    treed='exa --color=automatic --icons -DFTgh'                              \
    wget='wget --no-hsts'                                                     \
    zip='zip -rv'

# shortcuts
alias \
    eed='${EDITOR:?}'                      \
    seed='sudo ${EDITOR:?}'                \
    sx11="startx \"${XORGDIR:?}/xinitrc\"" \
    kx11="pkill -15 'X'"

# -----------------------------------------------------------------------------
# miscellaneous
# -----------------------------------------------------------------------------

alias \
    ascii="toilet -t -f '3d'"                                                  \
    tnet="ping 'example.com'"                                                  \
    yt='yt-dlp --restrict-filenames'                                           \
    ytf='yt-dlp -F'                                                            \
    ytt='yt-dlp --restrict-filenames --skip-download --write-thumbnail'        \
    yta="yt-dlp --restrict-filenames --prefer-ffmpeg --audio-format 'best' -x" \
    ytv="yt-dlp --restrict-filenames -f 'best'"

# [n]vi[m] -> nano
alias v='nvim'
