#!/usr/bin/env bash

# bspwmrc --- BSPWM configuration, written in BASH.

# Commentary:

# NOTE: The only reason why this script is not written in POSIX Sh is because
# of a few facilities bash brings in; bashisms should still be avoided for
# compatibility purposes.

# Code:

# shellcheck disable=SC2006,SC2190,SC2312

exe() {
    "${@}" &
}

bspwm_dir="${HOME}/.config/bspwm"
bar_dir="${HOME}/.config/polybar"

declare -A loads
loads=( \
    ['cfgs']="${bspwm_dir}/bspwm-cfgs"             \
    ['workspaces']="${bspwm_dir}/bspwm-workspaces" \
    ['rules']="${bspwm_dir}/bspwm-rules"           \

    # bar/panel
    ['bar']="${bar_dir}/polylaunch" \
)

for k in "${!loads[@]}"; do
    exe "${loads[${k}]}"
done

# binds
exe sxhkd -m 1 -t 2 -a 'Escape' -c "${bspwm_dir}/sxhkdrc"

exit 0
