#!/usr/bin/env bash

# .bashrc --- Bash shell configuration file

# shellcheck disable=1090
# follow non-constant sources

#  ██                        ██
# ░██                       ░██
# ░██       ██████    ██████░██      ██████  █████
# ░██████  ░░░░░░██  ██░░░░ ░██████ ░░██░░█ ██░░░██
# ░██░░░██  ███████ ░░█████ ░██░░░██ ░██ ░ ░██  ░░
# ░██  ░██ ██░░░░██  ░░░░░██░██  ░██ ░██   ░██   ██
# ░██████ ░░████████ ██████ ░██  ░██░███   ░░█████
# ░░░░░    ░░░░░░░░ ░░░░░░  ░░   ░░ ░░░     ░░░░░

# -----------------------------------------------------------------------------
# preamble
# -----------------------------------------------------------------------------

# do nothing if not running interactively
[[ ${-} != *i* ]] && return

setup_posix() {
    # **
    # sets up POSIX mode if available.
    # *

    test -z "${IN_NIX_SHELL}" && set -o posix
}

setup_posix ; unset -f setup_posix

# update the values of LINES and COLUMNS
test -n "${DISPLAY}" && shopt -s checkwinsize
shopt -s globstar      # allow ** to match recursively
shopt -s nocaseglob    # match globs case-insensitively
# attempt to correct directory names
shopt -s dirspell
shopt -s cdspell

# -----------------------------------------------------------------------------
# settings
# -----------------------------------------------------------------------------

# history
set -o history
shopt -s histappend # append to history
shopt -s cmdhist    # save multiline commands as one

export HISTFILE="${HOME}/.local/bash_history"
export HISTSIZE=-1
export HISTFILESIZE=-1
export HISTCONTROL='erasedups'        # keep duplicates off
export HISTIGNORE='cd:ls:ll:exit:pwd' # commands to be ignored in history

# -----------------------------------------------------------------------------
# sourcing
# -----------------------------------------------------------------------------

# prompt, aliases, functions...
test -x "${SHDIR}/aliasrc" && . "${SHDIR}/aliasrc"
test -x "${SHDIR}/functionrc" && . "${SHDIR}/functionrc"

# misc
for f in ${SHDIR}/plugins/*; do
    test -x "${f}" && . "${f}"
done

# -----------------------------------------------------------------------------
# prompt
# -----------------------------------------------------------------------------

PS1="\[\e[0;1;2;38;5;33m\][\[\e[0;38;5;197m\]\u\[\e[0;1;2;38;5;68m\]::\[\e[0;38;5;250m\]\h\[\e[0;1;2;38;5;33m\]] \[\e[0;1;2;38;5;33m\]@ \[\e[0;38;5;226m\]\w\n\[\e[0;1;2;38;5;33m\]╚══ \[\e[0;1;2;53;38;5;214m\]$? \[\e[0;38;5;192m\]$(__git_ps1 "(%s)") \[\e[0;1;2;38;5;46m\]\$ \[\e[0m\]"
