#!/bin/sh

# arch-tweaks --- Collection of tweaks for Arch-based distributions

# Commentary:

# Tweaks:
# - Colors for pacman
# - Parallel downloads for pacman
# - Enable all cores when compiling

# Code:

# checks
test `id -u` -ne 0 && printf 'This script needs root access.\n' >&2 && exit 1
test ! -x "`command -v 'pacman'`" \
    && printf 'This script only works on Arch-based systems.\n' \
    && exit 1

# variables
pacman_conf='/etc/pacman.conf'
makepkg_conf='/etc/makepkg.conf'

# backup
cp "${pacman_conf}" "${pacman_conf}-`date '+%Y%m%d-%H%M%S'`.bak"
cp "${makepkg_conf}" "${makepkg_conf}-`date '+%Y%m%d-%H%M%S'`.bak"

# pacman colors
sed -i "/^#Color$/a ILoveCandy" "${pacman_conf}"
sed -i "/^#Color$/s/#//" "${pacman_conf}"

# parallel downloads
sed -Ei "s/^#(ParallelDownloads\s=\s).*/\110/" "${pacman_conf}"

# use all cores for compilation
sed -Ei "s/^#(MAKEFLAGS=-j).*/\1`nproc`/" "${makepkg_conf}"

# reload pacman
pacman -Syy
