#!/bin/sh

# paru-setup --- Paru AUR helper setup

# Commentary:

# Paru is an AUR helper and pacman wrapper, an alternative to 'yay'

# References: https://github.com/Morganamilo/paru

# Code:

# -----------------------------------------------------------------------------
# preamble
# -----------------------------------------------------------------------------

die() {
    printf '%s\n' "${@}" >&2
    exit 1
}

# quit if not running an arch-based distro
! installedp 'pacman' && die 'Not running an Arch-based distribution'
rootp && die 'This CANNOT be ran as root'

# -----------------------------------------------------------------------------
# main
# -----------------------------------------------------------------------------

# only download & install if 'paru' is not installed already
if ! installedp 'paru'; then
    dest='/tmp/paru/'

    git-clone-fast 'https://aur.archlinux.org/paru.git' "${dest}"
    cd "${dest}" || die 'Could not cd, exiting...'
    makepkg --needed --noconfirm -Ccirs
else
    die "'paru' is already installed"
fi
