#!/usr/bin/env bash

# herbstluftwm

# This section contains the window manager's configuration written in /GNU Bash/.

# =herbstluftwm='s configuration file (=autostart=) must be an executable file;
# this comment will be appended in order to create the file itself.


# autostart --- annt's herbstluftwm

set -euo pipefail

# Preface

# Preliminary settings to set before anything else.


hc() {
    # **
    # since the `herbstclient` command is a lenghty, this function is used
    # instead.
    # *

    herbstclient "$@"
}



# Clean up mouse & keyboards binds before setting them, this is done in purpose
# to be effective on reload or when the window manager restarts.


hc emit_hook reload # force early reload
hc unlock           # unlock HLWM as it launches locked on X boot
hc unrule -F        # reset rules

# reset binds
hc keyunbind -F
hc mouseunbind --all

# Globals

# - Set the /Super/ key /a.k.a/ "/Windows/" key


Mod=Mod4

hc set tree_style '╾│ ├└╼─┐' # TODO: explore more styles

# Tags (Workspaces)

# - Declare tags from 1 to 9, name them as the literal numbers


tag_names=( {1..9} )
tag_keys=( {1..9} 0 )



# - Set previously declared tags and assign the /Super + =n= / keybinds, where
#   =n= is the tag number


hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# Monitors


# detect automatically, else HLWM treats as one big display if multiple monitors are present
# keep it at last
hc detect_monitors

# Settings


hc set focus_follows_mouse true

# Mouse binds


hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# Appearance


# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#222222cc'
hc set frame_border_normal_color '#101010cc'
hc set frame_bg_normal_color '#565656aa'
hc set frame_bg_active_color '#345F0Caa'
hc set frame_border_width 1
hc set always_show_frame on
hc set frame_bg_transparent on
hc set frame_transparent_width 5
hc set frame_gap 4

hc attr theme.title_height 15
hc attr theme.title_font 'Dejavu Sans:pixelsize=12'  # example using Xft
# hc attr theme.title_font '-*-fixed-medium-r-*-*-13-*-*-*-*-*-*-*'
hc attr theme.padding_top 2  # space below the title's baseline (i.e. text depth)
hc attr theme.active.color '#345F0Cef'
hc attr theme.title_color '#ffffff'
hc attr theme.normal.color '#323232dd'
hc attr theme.urgent.color '#7811A1dd'
hc attr theme.normal.title_color '#898989'
hc attr theme.inner_width 1
hc attr theme.inner_color black
hc attr theme.border_width 3
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color '#789161'
hc attr theme.urgent.inner_color '#9A65B0'
hc attr theme.normal.inner_color '#606060'
# copy inner color to outer_color
for state in active urgent normal ; do
    hc substitute C theme.${state}.inner_color \
        attr theme.${state}.outer_color C
done
hc attr theme.active.outer_width 1
hc attr theme.background_color '#141414'

hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings off
hc set smart_frame_surroundings on
hc set mouse_recenter_gap 0

# Rules


hc rule focus=on             # normally focus new clients
hc rule floatplacement=smart
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)'     floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG'                      focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

# Panel (Bar)


panel=${HOME}/.config/herbstluftwm/panel.sh
for monitor in $(hc list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    "$panel" "$monitor" &
done
