#!/bin/sh

#    ██
#   ░██
#  ██████  █████  ██   ██
# ░░░██░  ██░░░██░░██ ██
#   ░██  ░███████ ░░███
#   ░██  ░██░░░░   ██░██
#   ░░██ ░░██████ ██ ░░██
#    ░░   ░░░░░░ ░░   ░░

# -----------------------------------------------------------------------------
# preamble
# -----------------------------------------------------------------------------

# source utilities
# shellcheck disable=SC1090
. "$LIBSHUTILS/sys-utils"

# -----------------------------------------------------------------------------
# main
# -----------------------------------------------------------------------------

case $SYSTEM in
arch)
    # compiler & tools
    $PKG_INSTALL "texlive-most" "biber" "pandoc" "pandoc-citeproc"
    ;;

void)
    # check if running with elevated priviledges; elevate if not
    ! is_su && elevate_privs "$0" "$@"

    # compiler & tools
    $PKG_INSTALL "texlive-bin" "biber" "pandoc"

    # == tlmgr
    # gnupg is required to install via tlmgr
    $PKG_INSTALL "gnupg"

    # update
    tlmgr update --all

    tlmgr install biblatex
    tlmgr install biblatex-apa
    tlmgr install biblatex-ieee
    tlmgr install capt-of
    tlmgr install wrapfig

    # cleanup
    tlmgr update --all
    texhash
    ;;
esac

# -----------------------------------------------------------------------------
# references
# -----------------------------------------------------------------------------

# https://0x0.st/XmyQ
