#!/bin/sh

# setup-xbps-src --- Void Linux XBPS source packages collection setup

# Commentary:

# Downloads & installs the Void Linux XBPS source packages collection.

# References: https://github.com/void-linux/void-packages

# exit if not using void linux
! installed-p 'xbps-pkgdb' && err 'Not running Void Linux.' && exit 1

void_pkgs_path="${HOME}/.local/void-packages/"

# download void packages repo if not downloaded already
if test ! -d "${void_pkgs_path}"; then
    git clone --depth 1 'https://github.com/void-linux/void-packages.git' "${void_pkgs_path}"

    cd "${void_pkgs_path}" || die "Could not 'cd' into directory."

    # build packages marked as 'restricted'
    command echo XBPS_ALLOW_RESTRICTED=yes >> ./etc/conf

    ./xbps-src binary-bootstrap
else
    printf 'The Void packages repo is already installed, pulling from repo...\n'
    cd "${void_pkgs_path}" || die "Could not 'cd' into directory."

    # update repo
    git pull --force
fi

# cleanup
unset -v void_pkgs_path
