#!/bin/sh

# signal-setup --- Install Signal Client

# Commentary:

# Installs Signal Client.
# This script only works on Debian based distributions.

# References: https://signal.org/download/linux/

# do nothing if signal is installed already
installed-p 'signal-desktop' \
    && err 'Signal Cliente is already installed...' \
    && exit 1

# check if using Debian-like system
! installed-p 'apt-get' \
    && err 'This script only works on Debian-like systems.' \
    && exit 1
# quit if non-root
! root-p && err 'This scripts needs root access.' && exit 1

# 1. install official public software signing key
wget -O- 'https://updates.signal.org/desktop/apt/keys.asc' \
    | gpg --dearmor > '/tmp/signal-desktop-keyring.gpg'
cat '/tmp/signal-desktop-keyring.gpg' \
    | tee -a '/usr/share/keyrings/signal-desktop-keyring.gpg' > /dev/null

# 2. add signal repository to your list of repositories
echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/signal-desktop-keyring.gpg] https://updates.signal.org/desktop/apt xenial main' |\
    tee -a '/etc/apt/sources.list.d/signal-xenial.list'

# 3. update pkg database & install
apt update && apt install -y 'signal-desktop'
