#!/bin/sh

# spotify-setup --- Installs Spotify Client.

# Commentary:

# Installs Spotify Client.
# This script only works on Debian based distributions.

# References: https://www.spotify.com/ec/download/linux/

# do nothing if Spotify is installed already
installed-p 'spotify' \
    && err 'Spotify is already installed...' \
    && exit 1

# check if using Debian-like system
! installed-p 'apt-get' \
    && err 'This script only works on Debian-like systems.' \
    && exit 1
# quit if non-root
! root-p && err 'This scripts needs root access.' && exit 1

# add spotify's debian repo
curl -sS 'https://download.spotify.com/debian/pubkey_0D811D58.gpg' \
    | apt-key add - 
echo 'deb http://repository.spotify.com stable non-free' | tee '/etc/apt/sources.list.d/spotify.list'

# finally install
apt-get update && apt-get install -y 'spotify-client'
