---

- name: Ensure {{ local_dir }} dir exists
  file: path={{ local_dir }} state=directory

- name: Ensure {{ local_dir }}/share dir exists
  file: path={{ local_dir }}/share state=directory

- name: Ensure {{ local_dir }}/resources dir exists
  file: path={{ local_dir }}/resources state=directory

- name: Ensure {{ cfg_dir }} dir exists
  file: path={{ cfg_dir }} state=directory

- name: System upgrade
  become: true
  ansible.builtin.apt:
    update_cache: yes
    upgrade: full

- name: Install pkgs
  become: true
  ansible.builtin.apt:
    state: latest
    pkg:
      - curl
      - wget
      - git

      # coreutils
      - bat
      - fd-find
      - exa
      - ripgrep

      # archiving
      - atool
      - zip
      - unzip
      - p7zip
