---

- name: Ensure {{ local_dir }} dir exists
  file: path={{ local_dir }} state=directory

- name: Ensure {{ local_dir }}/share dir exists
  file: path={{ local_dir }}/share state=directory

- name: Ensure {{ local_dir }}/resources dir exists
  file: path={{ local_dir }}/resources state=directory

- name: Ensure {{ cfg_dir }} dir exists
  file: path={{ cfg_dir }} state=directory
