#+title:    *nixrice
#+author:   anntnzrb
#+language: en

#+property: header-args :exports code :results output verbatim


* table of contents :toc:noexport:
- [[#preamble][preamble]]
- [[#intro][intro]]
- [[#overview][overview]]
  - [[#binscripts][bin/scripts]]
- [[#installation][installation]]
  - [[#dependencies][dependencies]]
  - [[#instructions][instructions]]
- [[#disclaimer][disclaimer]]
- [[#log][log]]
- [[#copying][copying]]

* preamble

this file was originally created using /GNU Emacs' Org-Mode/, refer to
=./docs/= for the source code; you may also do so if you're reading thru a
Markdown/Org renderer.

* intro

these /.files/ have accompanied me since /2019/-ish (under VC since 2020), the
files (scripts) are written with portability in mind, meaning they're meant to
work across multiple [[https://0x0.st/HNfM][*nix distrubutions]].

* overview

a sneak peek of:

** bin/scripts

#+begin_src shell :exports results
tree -Fq ../.files/bin/.local/bin/ | head -n -2
#+end_src

#+RESULTS:
#+begin_example
../.files/bin/.local/bin/
├── compiler*
├── cpyclip*
├── dddev*
├── displayselect*
├── dmenumount*
├── dmenupass*
├── dmenuumount*
├── dmenuunicode*
├── editor*
├── fix-pkgs*
├── get-battery-cap*
├── get-brightness*
├── get-cpu-temp*
├── get-crypto*
├── get-epoch*
├── get-mem-usage*
├── get-net-traff*
├── get-torrent*
├── get-updates*
├── get-volume*
├── get-weather*
├── maimpick*
├── mkscript*
├── pfetch*
├── remaps*
├── setbg*
├── shorten-url*
├── sysfns*
├── sys-maintenance*
├── toggle-cmd*
├── upload-file*
└── utils/
    ├── err*
    ├── fast-git-clone*
    ├── installed-p*
    ├── internet-p*
    ├── README
    ├── root-p*
    └── running-p*
#+end_example

#+begin_src shell :exports results
tree -Fq ../.files/scripts/.local/scripts/ | head -n -2
#+end_src

#+RESULTS:
#+begin_example
../.files/scripts/.local/scripts/
├── arch/
│   └── arch-tweaks*
├── development/
│   ├── cheat-sheets*
│   ├── doom-emacs-setup.sh*
│   ├── jetbrains-toolbox-setup.sh*
│   ├── langs/
│   │   ├── android-dev*
│   │   ├── c-lang.sh*
│   │   ├── haskell-lang*
│   │   ├── java-lang.sh*
│   │   ├── json-lang*
│   │   ├── kotlin-lang.sh*
│   │   ├── markdown-lang*
│   │   ├── perl-lang*
│   │   ├── python-lang.sh*
│   │   ├── rust-lang*
│   │   ├── sh-lang*
│   │   └── tex-lang*
│   ├── paru-setup.sh*
│   ├── sdkman-setup.sh*
│   ├── virtualization*
│   └── vscode-extensions*
├── emacs-setup*
├── misc/
│   ├── gaming-setup*
│   └── vpn-setup*
├── nix-setup*
├── paru-setup*
├── pkgs/
│   ├── pkgs.csv
│   └── pkgs-setup*
├── signal-setup*
├── spotify-setup*
├── woeusb-setup*
└── xbps-src-setup*
#+end_example


* installation

somewhere around early /2022/ i switched from a bare git repo to using [[https://www.gnu.org/software/stow/][GNU Stow]]
to properly sync *.files*.

** dependencies

| dependencies | description                                               |
|--------------+-----------------------------------------------------------|
| [[https://git-scm.com/][Git]]          | (duh)                                                     |
| [[https://www.gnu.org/software/make/][GNU Make]]     | automation tool that generates builds executable programs |
| [[https://www.gnu.org/software/stow/][GNU Stow]]     | tool that deploys these dotfiles                          |

** instructions

get the repo and =cd= into it:

#+begin_src shell
git clone --depth 1 'https://gitlab.com/anntnzrb/xnixrice.git' '/tmp/annt-rice'

cd '/tmp/annt-rice'
#+end_src

#+RESULTS:


*OPTIONAL*: /you may take a look at the =Makefile= and add/remove the folders
to sync/

install:

#+begin_src shell
make install
#+end_src

#+RESULTS:

*NOTE*: /if an existing file is found =make= will throw an error and abort./

uninstall:

#+begin_src shell
make clean
#+end_src

#+RESULTS:

update (re-link):

#+begin_src shell
make reload
#+end_src

#+RESULTS:

* disclaimer

this repository serves as a laboratory. it's meant for experimentation and
should be considered /unstable/, /biased/ and sometimes even /untested/.

nevertheless feel free to take a look and learn from it, experimenting and
sharing is always encouraged.

* log

section designed to only track *very remarkable* stuff.

/(descending by date)/

*2022-05-08* - mass repo cleanup

- due to bad practices, this repo was filled with large blobs of files
  by the extentions ={png,ttf,otf}= (stored a few wallpapers + fonts).  *these
  blobs were pruned at the cost of the whole commit history being rewritten*.

*2022-04-26* - switch to /GNU Stow/.

- this repository literally emulated the structure of a =~/= directory
  prior to the switch.

*2021-06-02* - License switch /GPLv2/ -> /GPLv3/.

*2020-11-14* - /GNU Emacs/ is introduced.

* copying

refer to the [[./COPYING][COPYING]] file for licensing information.

unless otherwise noted, all code herein is distributed under the terms of the
[[https://www.gnu.org/licenses/gpl-3.0.en.html][GNU General Public License Version 3 or later]].

# local variables:
# eval: (add-hook 'after-save-hook 'org-babel-execute-buffer nil t)
# eval: (add-hook 'after-save-hook 'org-ascii-export-to-ascii nil t)
# eval: (add-hook 'after-save-hook (lambda () (rename-file "README.txt" "../README" t)) t)
# eval: (add-hook 'after-save-hook (lambda () (delete-file "README.txt")) t)
# end:
