#!/bin/sh

# defaults --- defaults for shell configuration file

export EDITOR="eeddiittoor"
export BROWSER='brave'
export FILE='pcmanfm'
export TERMINAL='alacritty'

export SH_DIR="${XDG_CONFIG_HOME:-${HOME}/.config}/sh"
export BASH_DIR="${XDG_CONFIG_HOME:-${HOME}/.config}/bash"

#------------------------------------------------------------------------------
# clean-up
#------------------------------------------------------------------------------
# nothing too specific, just for cleaning up ~/

export GNUPGHOME="${HOME}/.config/gnupg"
export WGETRC="${HOME}/.config/wget/wgetrc"
export LESSKEY="${HOME}/.config/less/lesskey"
export LESSHISTFILE='-'

# GTK
export GTK_RC_FILES="${HOME}/.config/gtk-1.0/gtkrc"
export GTK2_RC_FILES="${HOME}/.config/gtk-2.0/gtkrc"

# Android
export ANDROID_SDK_HOME="${HOME}/.config/android"
export ANDROID_AVD_HOME="${HOME}/.local/share/android"
export ANDROID_EMULATOR_HOME="${HOME}/.local/share/android"
export ADB_VENDOR_KEY="${HOME}/.config/android"

# Ansible
export ANSIBLE_HOME="${HOME}/.config/ansible"
export ANSIBLE_CONFIG="${ANSIBLE_HOME}/ansible.cfg"
export ANSIBLE_GALAXY_CACHE_DIR="${ANSIBLE_HOME}/galaxy_cache"

# JVM-related
export LEIN_HOME="${HOME}/.config/lein"

# Web
export NPM_CONFIG_USERCONFIG="${HOME}/.config/npm/npmrc"
