---

- name: Set variables
  set_fact:
    bw_zip: '/tmp/bw.zip'
    bw_dir: '/usr/local/bin'

- name: Download
  ansible.builtin.get_url:
    url: 'https://vault.bitwarden.com/download/?app=cli&platform=linux'
    dest: "{{ bw_zip }}"

- name: Install
  become: true
  ansible.builtin.unarchive:
    src: "{{ bw_zip }}"
    dest: "{{ bw_dir }}"
    mode: 0755

