#!/bin/sh

# xinitrc --- Xorg initialization file

# Commentary:

# This file runs when the display server is invoked, the following are executed
# before the WM/DE is launched.

# Code:

# shellcheck disable=SC2006,SC2312

# -----------------------------------------------------------------------------
# configuration
# -----------------------------------------------------------------------------
# '1' -> true ; blank -> false

use_tray=1
use_xrdb=

# -----------------------------------------------------------------------------
# main
# -----------------------------------------------------------------------------

{
    # **
    # Apps: launched when graphical session is started.
    # *

    "${TERMINAL:?}" -e 'htop' & # system monitor

    remaps   & # keyboard settings
    setbg    & # wallpaper
    picom -b & # compositor
    dunst    & # notification daemon
    xbanish  & # hide mouse when typing

    # global keybindings
    sxhkd -m 1 -t 2 -a 'Escape' -c "${HOME}/.config/sxhkd/sxhkdrc" &

    # light filter
    redshift -l "`curl -Ss 'https://location.services.mozilla.com/v1/geolocate?key=geoclue' \
                    | awk 'OFS=":" { print $3,$5 }' | tr -d ',}'`" &
}

{
    # **
    # Applets: require a bar/panel which supports & displays them.
    # *

    test "${use_tray}" || return 0

    nm-applet & # NetworkManager
    pasystray & # audio (pulseaudio/pipewire)
}

{
    # **
    # Audio
    # *

    pipewire       &
    pipewire-pulse &
    wireplumber    &
    pasystray      &
}

{
    # **
    # Xorg: DPI, timeouts, etc...
    # *

    xrandr --dpi 92    & # DPI defaulted to 1920x1080 24" screen
    xset s off         & # disable screensaver
    xset dpms 0 0 900  & # off-screen time

    # Xresources
    test "${use_xrdb}" || return 0

    xrdb "${XORG_DIR:?}/Xresources"
}
