---

- name: config
  become: true
  ansible.builtin.copy:
    src: "{{ role_path }}/files/grub"
    dest: '/etc/default/grub'

- name: Update
  become: true
  ansible.builtin.shell: grub-mkconfig -o /boot/grub/grub.cfg
