name: Nix Flake Daily Inputs Update

on:
  workflow_dispatch: # manual triggering
  schedule:
  - cron: "2 6 * * *"

permissions:
  contents: write

env:
  # all the flake inputs that shall be updated daily
  NIX_INPUTS: "nixpkgs-unstable nurpkgs" 

jobs:
  flake-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@v14

      - name: Configure Git
        run: |
          git config user.name 'github-actions'
          git config user.email 'actions@github.com'

      - name: Update Flake Inputs
        run: |
          for input in $NIX_INPUTS; do
            nix flake update "$input" --commit-lock-file --option commit-lockfile-summary "chore(flake): update input ($input)"
          done

      - name: Push Updates
        run: git pull --rebase --autostash && git push
