name: Nix Flake Update

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  flake-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Configure Git
        run: |
          git config user.name 'github-actions'
          git config user.email 'actions@github.com'

      - name: Update Flake Inputs
        run: |
          nix flake update || exit 1
          git commit -m "chore(flake): bump inputs" flake.lock || :

      - name: Push Updates
        run: |
          git pull --rebase --autostash
          git push
