name: "Nix CI"

on:
  workflow_dispatch: # manual triggering
  pull_request:
  push:
    branches:
      - dev

jobs:
  ci:
    runs-on: ${{ matrix.system }}
    strategy:
      matrix:
        system: [x86_64-linux, aarch64-darwin]
    steps:
      - uses: actions/checkout@v4
      - run: om ci run --systems "${{ matrix.system }}" -- --show-trace
