name: Nix Flake Lock Input Update

on:
  workflow_dispatch:
  schedule:
    - cron: "5 6 * * 1"

permissions:
  contents: write
  pull-requests: write

jobs:
  update-lockfile:
    uses: ./.github/workflows/update-flake-lock.yml
    with:
      update_inputs: nixpkgs-unstable nurpkgs
